# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.BusTrip do
  @moduledoc """
  A trip on a commercial bus line.

  Helper for building a Schema.org [BusTrip](https://schema.org/BusTrip) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:arrival_bus_stop) =>
              SEO.JSONLD.BusStation.t() | map() | SEO.JSONLD.BusStop.t(),
            optional(:bus_name) => String.t(),
            optional(:bus_number) => String.t(),
            optional(:departure_bus_stop) =>
              SEO.JSONLD.BusStation.t() | map() | SEO.JSONLD.BusStop.t(),
            optional(:arrival_time) => DateTime.t() | NaiveDateTime.t() | String.t() | Time.t(),
            optional(:departure_time) => DateTime.t() | NaiveDateTime.t() | String.t() | Time.t(),
            optional(:itinerary) => SEO.JSONLD.Place.t() | map() | SEO.JSONLD.ItemList.t(),
            optional(:offers) => SEO.JSONLD.Offer.t() | map() | SEO.JSONLD.Demand.t(),
            optional(:part_of_trip) => SEO.JSONLD.Trip.t() | map(),
            optional(:provider) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:sub_trip) => SEO.JSONLD.Trip.t() | map(),
            optional(:trip_origin) => SEO.JSONLD.Place.t() | map(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              arrival_bus_stop: SEO.JSONLD.BusStation.t() | map() | SEO.JSONLD.BusStop.t(),
              bus_name: String.t(),
              bus_number: String.t(),
              departure_bus_stop: SEO.JSONLD.BusStation.t() | map() | SEO.JSONLD.BusStop.t(),
              arrival_time: DateTime.t() | NaiveDateTime.t() | String.t() | Time.t(),
              departure_time: DateTime.t() | NaiveDateTime.t() | String.t() | Time.t(),
              itinerary: SEO.JSONLD.Place.t() | map() | SEO.JSONLD.ItemList.t(),
              offers: SEO.JSONLD.Offer.t() | map() | SEO.JSONLD.Demand.t(),
              part_of_trip: SEO.JSONLD.Trip.t() | map(),
              provider: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              sub_trip: SEO.JSONLD.Trip.t() | map(),
              trip_origin: SEO.JSONLD.Place.t() | map(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"BusTrip"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{}
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :arrival_bus_stop => "arrivalBusStop",
    :arrival_time => "arrivalTime",
    :bus_name => "busName",
    :bus_number => "busNumber",
    :departure_bus_stop => "departureBusStop",
    :departure_time => "departureTime",
    :disambiguating_description => "disambiguatingDescription",
    :main_entity_of_page => "mainEntityOfPage",
    :part_of_trip => "partOfTrip",
    :potential_action => "potentialAction",
    :same_as => "sameAs",
    :sub_trip => "subTrip",
    :subject_of => "subjectOf",
    :trip_origin => "tripOrigin"
  }

  @doc """
  Build a BusTrip JSON-LD map.

  ## Fields

  - `:arrival_bus_stop` - The stop or station from which the bus arrives.
  - `:bus_name` - The name of the bus (e.g. Bolt Express).
  - `:bus_number` - The unique identifier for the bus.
  - `:departure_bus_stop` - The stop or station from which the bus departs.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Trip`
  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "BusTrip")
  end
end
