# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.Error do
  @moduledoc """
  Representation of an Error.

  Helper for building a Schema.org [Error](https://schema.org/Error) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:error_code) =>
              :active_action_status
              | :completed_action_status
              | :event_cancelled
              | :event_moved_online
              | :event_postponed
              | :event_rescheduled
              | :event_scheduled
              | :failed_action_status
              | :in_force
              | :not_in_force
              | :offline_permanently
              | :offline_temporarily
              | :online
              | :online_full
              | :order_cancelled
              | :order_delivered
              | :order_in_transit
              | :order_payment_due
              | :order_pickup_available
              | :order_problem
              | :order_processing
              | :order_returned
              | :partially_in_force
              | :payment_automatically_applied
              | :payment_complete
              | :payment_declined
              | :payment_due
              | :payment_past_due
              | :potential_action_status
              | :reservation_cancelled
              | :reservation_confirmed
              | :reservation_hold
              | :reservation_pending
              | integer()
              | SEO.JSONLD.DefinedTerm.t()
              | map()
              | String.t(),
            optional(:data) => SEO.JSONLD.Thing.t() | map(),
            optional(:source) => SEO.JSONLD.Thing.t() | map(),
            optional(:timestamp) => DateTime.t() | NaiveDateTime.t() | String.t(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              error_code:
                :active_action_status
                | :completed_action_status
                | :event_cancelled
                | :event_moved_online
                | :event_postponed
                | :event_rescheduled
                | :event_scheduled
                | :failed_action_status
                | :in_force
                | :not_in_force
                | :offline_permanently
                | :offline_temporarily
                | :online
                | :online_full
                | :order_cancelled
                | :order_delivered
                | :order_in_transit
                | :order_payment_due
                | :order_pickup_available
                | :order_problem
                | :order_processing
                | :order_returned
                | :partially_in_force
                | :payment_automatically_applied
                | :payment_complete
                | :payment_declined
                | :payment_due
                | :payment_past_due
                | :potential_action_status
                | :reservation_cancelled
                | :reservation_confirmed
                | :reservation_hold
                | :reservation_pending
                | integer()
                | SEO.JSONLD.DefinedTerm.t()
                | map()
                | String.t(),
              data: SEO.JSONLD.Thing.t() | map(),
              source: SEO.JSONLD.Thing.t() | map(),
              timestamp: DateTime.t() | NaiveDateTime.t() | String.t(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"Error"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{
    :error_code => %{
      :active_action_status => "https://schema.org/ActiveActionStatus",
      :completed_action_status => "https://schema.org/CompletedActionStatus",
      :event_cancelled => "https://schema.org/EventCancelled",
      :event_moved_online => "https://schema.org/EventMovedOnline",
      :event_postponed => "https://schema.org/EventPostponed",
      :event_rescheduled => "https://schema.org/EventRescheduled",
      :event_scheduled => "https://schema.org/EventScheduled",
      :failed_action_status => "https://schema.org/FailedActionStatus",
      :in_force => "https://schema.org/InForce",
      :not_in_force => "https://schema.org/NotInForce",
      :offline_permanently => "https://schema.org/OfflinePermanently",
      :offline_temporarily => "https://schema.org/OfflineTemporarily",
      :online => "https://schema.org/Online",
      :online_full => "https://schema.org/OnlineFull",
      :order_cancelled => "https://schema.org/OrderCancelled",
      :order_delivered => "https://schema.org/OrderDelivered",
      :order_in_transit => "https://schema.org/OrderInTransit",
      :order_payment_due => "https://schema.org/OrderPaymentDue",
      :order_pickup_available => "https://schema.org/OrderPickupAvailable",
      :order_problem => "https://schema.org/OrderProblem",
      :order_processing => "https://schema.org/OrderProcessing",
      :order_returned => "https://schema.org/OrderReturned",
      :partially_in_force => "https://schema.org/PartiallyInForce",
      :payment_automatically_applied => "https://schema.org/PaymentAutomaticallyApplied",
      :payment_complete => "https://schema.org/PaymentComplete",
      :payment_declined => "https://schema.org/PaymentDeclined",
      :payment_due => "https://schema.org/PaymentDue",
      :payment_past_due => "https://schema.org/PaymentPastDue",
      :potential_action_status => "https://schema.org/PotentialActionStatus",
      :reservation_cancelled => "https://schema.org/ReservationCancelled",
      :reservation_confirmed => "https://schema.org/ReservationConfirmed",
      :reservation_hold => "https://schema.org/ReservationHold",
      :reservation_pending => "https://schema.org/ReservationPending"
    }
  }
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :disambiguating_description => "disambiguatingDescription",
    :error_code => "errorCode",
    :main_entity_of_page => "mainEntityOfPage",
    :potential_action => "potentialAction",
    :same_as => "sameAs",
    :subject_of => "subjectOf"
  }

  @doc """
  Build a Error JSON-LD map.

  ## Fields

  - `:error_code` - Application or platform dependant error code. One of: `:active_action_status`, `:completed_action_status`, `:event_cancelled`, `:event_moved_online`, `:event_postponed`, `:event_rescheduled`, `:event_scheduled`, `:failed_action_status`, `:in_force`, `:not_in_force`, `:offline_permanently`, `:offline_temporarily`, `:online`, `:online_full`, `:order_cancelled`, `:order_delivered`, `:order_in_transit`, `:order_payment_due`, `:order_pickup_available`, `:order_problem`, `:order_processing`, `:order_returned`, `:partially_in_force`, `:payment_automatically_applied`, `:payment_complete`, `:payment_declined`, `:payment_due`, `:payment_past_due`, `:potential_action_status`, `:reservation_cancelled`, `:reservation_confirmed`, `:reservation_hold`, `:reservation_pending`.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.InstantaneousEvent`
  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "Error")
  end
end
