# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.ExchangeRateSpecification do
  @moduledoc """
  A structured value representing exchange rate.

  Helper for building a Schema.org [ExchangeRateSpecification](https://schema.org/ExchangeRateSpecification) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:currency) => String.t(),
            optional(:current_exchange_rate) => SEO.JSONLD.UnitPriceSpecification.t() | map(),
            optional(:exchange_rate_spread) => SEO.JSONLD.MonetaryAmount.t() | map() | number(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              currency: String.t(),
              current_exchange_rate: SEO.JSONLD.UnitPriceSpecification.t() | map(),
              exchange_rate_spread: SEO.JSONLD.MonetaryAmount.t() | map() | number(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"ExchangeRateSpecification"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{}
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :current_exchange_rate => "currentExchangeRate",
    :disambiguating_description => "disambiguatingDescription",
    :exchange_rate_spread => "exchangeRateSpread",
    :main_entity_of_page => "mainEntityOfPage",
    :potential_action => "potentialAction",
    :same_as => "sameAs",
    :subject_of => "subjectOf"
  }

  @doc """
  Build a ExchangeRateSpecification JSON-LD map.

  ## Fields

  - `:currency` - The currency in which the monetary amount is expressed.

  Use standard formats: [ISO 4217 currency format](http://en.wikipedia.org/wiki/ISO_4217), e.g. "USD"; [Ticker symbol](https://en.wikipedia.org/wiki/List_of_cryptocurrencies) for cryptocurrencies, e.g. "BTC"; well known names for [Local Exchange Trading Systems](https://en.wikipedia.org/wiki/Local_exchange_trading_system) (LETS) and other currency types, e.g. "Ithaca HOUR".
  - `:current_exchange_rate` - The current price of a currency.
  - `:exchange_rate_spread` - The difference between the price at which a broker or other intermediary buys and sells foreign currency.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "ExchangeRateSpecification")
  end
end
