# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.FloorPlan do
  @moduledoc """
  A FloorPlan is an explicit representation of a collection of similar accommodations, allowing the provision of common information (room counts, sizes, layout diagrams) and offers for rental or sale. In typical use, some `SEO.JSONLD.ApartmentComplex` has an `accommodationFloorPlan` which is a `SEO.JSONLD.FloorPlan`. A FloorPlan is always in the context of a particular place, either a larger `SEO.JSONLD.ApartmentComplex` or a single `SEO.JSONLD.Apartment`. The visual/spatial aspects of a floor plan (i.e. room layout, [see wikipedia](https://en.wikipedia.org/wiki/Floor_plan)) can be indicated using `image`.

  Helper for building a Schema.org [FloorPlan](https://schema.org/FloorPlan) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:amenity_feature) => SEO.JSONLD.LocationFeatureSpecification.t() | map(),
            optional(:floor_size) => SEO.JSONLD.QuantitativeValue.t() | map(),
            optional(:is_plan_for_apartment) => SEO.JSONLD.Accommodation.t() | map(),
            optional(:layout_image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:number_of_accommodation_units) => SEO.JSONLD.QuantitativeValue.t() | map(),
            optional(:number_of_available_accommodation_units) =>
              SEO.JSONLD.QuantitativeValue.t() | map(),
            optional(:number_of_bathrooms_total) => integer(),
            optional(:number_of_bedrooms) => SEO.JSONLD.QuantitativeValue.t() | map() | number(),
            optional(:number_of_full_bathrooms) => number(),
            optional(:number_of_partial_bathrooms) => number(),
            optional(:number_of_rooms) => SEO.JSONLD.QuantitativeValue.t() | map() | number(),
            optional(:pets_allowed) => String.t() | boolean(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              amenity_feature: SEO.JSONLD.LocationFeatureSpecification.t() | map(),
              floor_size: SEO.JSONLD.QuantitativeValue.t() | map(),
              is_plan_for_apartment: SEO.JSONLD.Accommodation.t() | map(),
              layout_image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              number_of_accommodation_units: SEO.JSONLD.QuantitativeValue.t() | map(),
              number_of_available_accommodation_units: SEO.JSONLD.QuantitativeValue.t() | map(),
              number_of_bathrooms_total: integer(),
              number_of_bedrooms: SEO.JSONLD.QuantitativeValue.t() | map() | number(),
              number_of_full_bathrooms: number(),
              number_of_partial_bathrooms: number(),
              number_of_rooms: SEO.JSONLD.QuantitativeValue.t() | map() | number(),
              pets_allowed: String.t() | boolean(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"FloorPlan"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{}
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :amenity_feature => "amenityFeature",
    :disambiguating_description => "disambiguatingDescription",
    :floor_size => "floorSize",
    :is_plan_for_apartment => "isPlanForApartment",
    :layout_image => "layoutImage",
    :main_entity_of_page => "mainEntityOfPage",
    :number_of_accommodation_units => "numberOfAccommodationUnits",
    :number_of_available_accommodation_units => "numberOfAvailableAccommodationUnits",
    :number_of_bathrooms_total => "numberOfBathroomsTotal",
    :number_of_bedrooms => "numberOfBedrooms",
    :number_of_full_bathrooms => "numberOfFullBathrooms",
    :number_of_partial_bathrooms => "numberOfPartialBathrooms",
    :number_of_rooms => "numberOfRooms",
    :pets_allowed => "petsAllowed",
    :potential_action => "potentialAction",
    :same_as => "sameAs",
    :subject_of => "subjectOf"
  }

  @doc """
  Build a FloorPlan JSON-LD map.

  ## Fields

  - `:amenity_feature` - An amenity feature (e.g. a characteristic or service) of the Accommodation. This generic property does not make a statement about whether the feature is included in an offer for the main accommodation or available at extra costs.
  - `:floor_size` - The size of the accommodation, e.g. in square meter or squarefoot.
  Typical unit code(s): MTK for square meter, FTK for square foot, or YDK for square yard.
  - `:is_plan_for_apartment` - Indicates some accommodation that this floor plan describes.
  - `:layout_image` - A schematic image showing the floorplan layout.
  - `:number_of_accommodation_units` - Indicates the total (available plus unavailable) number of accommodation units in an `SEO.JSONLD.ApartmentComplex`, or the number of accommodation units for a specific `SEO.JSONLD.FloorPlan` (within its specific `SEO.JSONLD.ApartmentComplex`). See also `numberOfAvailableAccommodationUnits`.
  - `:number_of_available_accommodation_units` - Indicates the number of available accommodation units in an `SEO.JSONLD.ApartmentComplex`, or the number of accommodation units for a specific `SEO.JSONLD.FloorPlan` (within its specific `SEO.JSONLD.ApartmentComplex`). See also `numberOfAccommodationUnits`.
  - `:number_of_bathrooms_total` - The total integer number of bathrooms in some `SEO.JSONLD.Accommodation`, following real estate conventions as [documented in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsTotalInteger+Field): "The simple sum of the number of bathrooms. For example for a property with two Full Bathrooms and one Half Bathroom, the Bathrooms Total Integer will be 3.". See also `numberOfRooms`.
  - `:number_of_bedrooms` - The total integer number of bedrooms in a some `SEO.JSONLD.Accommodation`, `SEO.JSONLD.ApartmentComplex` or `SEO.JSONLD.FloorPlan`.
  - `:number_of_full_bathrooms` - Number of full bathrooms - The total number of full and ¾ bathrooms in an `SEO.JSONLD.Accommodation`. This corresponds to the [BathroomsFull field in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsFull+Field).
  - `:number_of_partial_bathrooms` - Number of partial bathrooms - The total number of half and ¼ bathrooms in an `SEO.JSONLD.Accommodation`. This corresponds to the [BathroomsPartial field in RESO](https://ddwiki.reso.org/display/DDW17/BathroomsPartial+Field).
  - `:number_of_rooms` - The number of rooms (excluding bathrooms and closets) of the accommodation or lodging business.
  Typical unit code(s): ROM for room or C62 for no unit. The type of room can be put in the unitText property of the QuantitativeValue.
  - `:pets_allowed` - Indicates whether pets are allowed to enter the accommodation or lodging business. More detailed information can be put in a text value.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "FloorPlan")
  end
end
