# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.JobPosting do
  @moduledoc """
  A listing that describes a job opening in a certain organization.

  ![JobPosting rich-result example](./assets/jobs-search-example.png)

  ## Example

  ```elixir
  SEO.JSONLD.JobPosting.build(%{
    title: "Senior Elixir Engineer",
    description: "Build distributed systems in Elixir.",
    date_posted: ~D[2024-03-01],
    valid_through: ~D[2024-06-01],
    employment_type: "FULL_TIME",
    hiring_organization:
      SEO.JSONLD.Organization.build(%{
        name: "Acme",
        same_as: "https://acme.com",
        logo: "https://acme.com/logo.png"
      }),
    job_location:
      SEO.JSONLD.Place.build(%{
        address:
          SEO.JSONLD.PostalAddress.build(%{
            street_address: "1600 Amphitheatre Pkwy",
            address_locality: "Mountain View",
            address_region: "CA",
            postal_code: "94043",
            address_country: "US"
          })
      }),
    base_salary:
      SEO.JSONLD.MonetaryAmount.build(%{
        currency: "USD",
        value:
          SEO.JSONLD.QuantitativeValue.build(%{
            value: 175_000,
            unit_text: "YEAR"
          })
      })
  })
  ```

  Helper for building a Schema.org [JobPosting](https://schema.org/JobPosting) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:applicant_location_requirements) =>
              SEO.JSONLD.AdministrativeArea.t() | map(),
            optional(:application_contact) => SEO.JSONLD.ContactPoint.t() | map(),
            optional(:base_salary) =>
              SEO.JSONLD.PriceSpecification.t() | map() | number() | SEO.JSONLD.MonetaryAmount.t(),
            optional(:benefits) => String.t(),
            required(:date_posted) => DateTime.t() | NaiveDateTime.t() | String.t() | Date.t(),
            optional(:direct_apply) => boolean(),
            optional(:education_requirements) =>
              SEO.JSONLD.EducationalOccupationalCredential.t() | map() | String.t(),
            optional(:eligibility_to_work_requirement) => String.t(),
            optional(:employer_overview) => String.t(),
            optional(:employment_type) => String.t(),
            optional(:employment_unit) => SEO.JSONLD.Organization.t() | map(),
            optional(:estimated_salary) =>
              SEO.JSONLD.MonetaryAmountDistribution.t()
              | map()
              | SEO.JSONLD.MonetaryAmount.t()
              | number(),
            optional(:experience_in_place_of_education) => boolean(),
            optional(:experience_requirements) =>
              String.t() | SEO.JSONLD.OccupationalExperienceRequirements.t() | map(),
            required(:hiring_organization) =>
              SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:incentive_compensation) => String.t(),
            optional(:incentives) => String.t(),
            optional(:industry) => SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
            optional(:job_benefits) => String.t(),
            optional(:job_duration) =>
              SEO.JSONLD.QuantitativeValue.t() | map() | Duration.t() | String.t(),
            optional(:job_immediate_start) => boolean(),
            optional(:job_location) => SEO.JSONLD.Place.t() | map(),
            optional(:job_location_type) => String.t(),
            optional(:job_start_date) => Date.t() | String.t(),
            optional(:occupational_category) => SEO.JSONLD.CategoryCode.t() | map() | String.t(),
            optional(:physical_requirement) =>
              String.t() | URI.t() | SEO.JSONLD.DefinedTerm.t() | map(),
            optional(:qualifications) => SEO.JSONLD.Credential.t() | map() | String.t(),
            optional(:relevant_occupation) => SEO.JSONLD.Occupation.t() | map(),
            optional(:responsibilities) => String.t(),
            optional(:salary_currency) => String.t(),
            optional(:security_clearance_requirement) => String.t() | URI.t(),
            optional(:sensory_requirement) =>
              SEO.JSONLD.DefinedTerm.t() | map() | String.t() | URI.t(),
            optional(:skills) => String.t() | SEO.JSONLD.DefinedTerm.t() | map(),
            optional(:special_commitments) => String.t(),
            required(:title) => String.t(),
            optional(:total_job_openings) => integer(),
            optional(:valid_through) => DateTime.t() | NaiveDateTime.t() | String.t() | Date.t(),
            optional(:work_hours) => String.t(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            required(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              applicant_location_requirements: SEO.JSONLD.AdministrativeArea.t() | map(),
              application_contact: SEO.JSONLD.ContactPoint.t() | map(),
              base_salary:
                SEO.JSONLD.PriceSpecification.t()
                | map()
                | number()
                | SEO.JSONLD.MonetaryAmount.t(),
              benefits: String.t(),
              date_posted: DateTime.t() | NaiveDateTime.t() | String.t() | Date.t(),
              direct_apply: boolean(),
              education_requirements:
                SEO.JSONLD.EducationalOccupationalCredential.t() | map() | String.t(),
              eligibility_to_work_requirement: String.t(),
              employer_overview: String.t(),
              employment_type: String.t(),
              employment_unit: SEO.JSONLD.Organization.t() | map(),
              estimated_salary:
                SEO.JSONLD.MonetaryAmountDistribution.t()
                | map()
                | SEO.JSONLD.MonetaryAmount.t()
                | number(),
              experience_in_place_of_education: boolean(),
              experience_requirements:
                String.t() | SEO.JSONLD.OccupationalExperienceRequirements.t() | map(),
              hiring_organization: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              incentive_compensation: String.t(),
              incentives: String.t(),
              industry: SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
              job_benefits: String.t(),
              job_duration: SEO.JSONLD.QuantitativeValue.t() | map() | Duration.t() | String.t(),
              job_immediate_start: boolean(),
              job_location: SEO.JSONLD.Place.t() | map(),
              job_location_type: String.t(),
              job_start_date: Date.t() | String.t(),
              occupational_category: SEO.JSONLD.CategoryCode.t() | map() | String.t(),
              physical_requirement: String.t() | URI.t() | SEO.JSONLD.DefinedTerm.t() | map(),
              qualifications: SEO.JSONLD.Credential.t() | map() | String.t(),
              relevant_occupation: SEO.JSONLD.Occupation.t() | map(),
              responsibilities: String.t(),
              salary_currency: String.t(),
              security_clearance_requirement: String.t() | URI.t(),
              sensory_requirement: SEO.JSONLD.DefinedTerm.t() | map() | String.t() | URI.t(),
              skills: String.t() | SEO.JSONLD.DefinedTerm.t() | map(),
              special_commitments: String.t(),
              title: String.t(),
              total_job_openings: integer(),
              valid_through: DateTime.t() | NaiveDateTime.t() | String.t() | Date.t(),
              work_hours: String.t(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"JobPosting"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{}
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :applicant_location_requirements => "applicantLocationRequirements",
    :application_contact => "applicationContact",
    :base_salary => "baseSalary",
    :date_posted => "datePosted",
    :direct_apply => "directApply",
    :disambiguating_description => "disambiguatingDescription",
    :education_requirements => "educationRequirements",
    :eligibility_to_work_requirement => "eligibilityToWorkRequirement",
    :employer_overview => "employerOverview",
    :employment_type => "employmentType",
    :employment_unit => "employmentUnit",
    :estimated_salary => "estimatedSalary",
    :experience_in_place_of_education => "experienceInPlaceOfEducation",
    :experience_requirements => "experienceRequirements",
    :hiring_organization => "hiringOrganization",
    :incentive_compensation => "incentiveCompensation",
    :job_benefits => "jobBenefits",
    :job_duration => "jobDuration",
    :job_immediate_start => "jobImmediateStart",
    :job_location => "jobLocation",
    :job_location_type => "jobLocationType",
    :job_start_date => "jobStartDate",
    :main_entity_of_page => "mainEntityOfPage",
    :occupational_category => "occupationalCategory",
    :physical_requirement => "physicalRequirement",
    :potential_action => "potentialAction",
    :relevant_occupation => "relevantOccupation",
    :salary_currency => "salaryCurrency",
    :same_as => "sameAs",
    :security_clearance_requirement => "securityClearanceRequirement",
    :sensory_requirement => "sensoryRequirement",
    :special_commitments => "specialCommitments",
    :subject_of => "subjectOf",
    :total_job_openings => "totalJobOpenings",
    :valid_through => "validThrough",
    :work_hours => "workHours"
  }

  @doc """
  Build a JobPosting JSON-LD map.

  ## Fields

  - `:applicant_location_requirements` - The location(s) applicants can apply from. This is usually used for telecommuting jobs where the applicant does not need to be in a physical office. Note: This should not be used for citizenship or work visa requirements.
  - `:application_contact` - Contact details for further information relevant to this job posting.
  - `:base_salary` - The base salary of the job or of an employee in an EmployeeRole.
  - `:benefits` - Description of benefits associated with the job.
  - `:date_posted` - Publication date of an online listing.
  - `:direct_apply` - Indicates whether an `url` that is associated with a `SEO.JSONLD.JobPosting` enables direct application for the job, via the posting website. A job posting is considered to have directApply of `True` if an application process for the specified job can be directly initiated via the url(s) given (noting that e.g. multiple internet domains might nevertheless be involved at an implementation level). A value of `False` is appropriate if there is no clear path to applying directly online for the specified job, navigating directly from the JobPosting url(s) supplied.
  - `:education_requirements` - Educational background needed for the position or Occupation.
  - `:eligibility_to_work_requirement` - The legal requirements such as citizenship, visa and other documentation required for an applicant to this job.
  - `:employer_overview` - A description of the employer, career opportunities and work environment for this position.
  - `:employment_type` - Type of employment (e.g. full-time, part-time, contract, temporary, seasonal, internship).
  - `:employment_unit` - Indicates the department, unit and/or facility where the employee reports and/or in which the job is to be performed.
  - `:estimated_salary` - An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.
  - `:experience_in_place_of_education` - Indicates whether a `SEO.JSONLD.JobPosting` will accept experience (as indicated by `SEO.JSONLD.OccupationalExperienceRequirements`) in place of its formal educational qualifications (as indicated by `educationRequirements`). If true, indicates that satisfying one of these requirements is sufficient.
  - `:experience_requirements` - Description of skills and experience needed for the position or Occupation.
  - `:hiring_organization` - Organization or Person offering the job position.
  - `:incentive_compensation` - Description of bonus and commission compensation aspects of the job.
  - `:incentives` - Description of bonus and commission compensation aspects of the job.
  - `:industry` - The industry associated with the job position.
  - `:job_benefits` - Description of benefits associated with the job.
  - `:job_duration` - The expected duration of an employment offer as advertised by the employer. Relevant for job postings that have a clearly defined period in mind such as seasonal work, substitutes for maternal leave or any other temporary employment.
  - `:job_immediate_start` - An indicator as to whether a position is available for an immediate start.
  - `:job_location` - A (typically single) geographic location associated with the job position.
  - `:job_location_type` - A description of the job location (e.g. TELECOMMUTE for telecommute jobs).
  - `:job_start_date` - The date on which a successful applicant for this job would be expected to start work. Choose a specific date in the future or use the jobImmediateStart property to indicate the position is to be filled as soon as possible.
  - `:occupational_category` - A category describing the job, preferably using a term from a taxonomy such as [BLS O*NET-SOC](http://www.onetcenter.org/taxonomy.html), [ISCO-08](https://www.ilo.org/public/english/bureau/stat/isco/isco08/) or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.

  Note: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.
  - `:physical_requirement` - A description of the types of physical activity associated with the job. Defined terms such as those in O*net may be used, but note that there is no way to specify the level of ability as well as its nature when using a defined term.
  - `:qualifications` - Specific qualifications required for this role or Occupation.
  - `:relevant_occupation` - The Occupation for the JobPosting.
  - `:responsibilities` - Responsibilities associated with this role or Occupation.
  - `:salary_currency` - The currency (coded using [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217)) used for the main salary information in this job posting or for this employee.
  - `:security_clearance_requirement` - A description of any security clearance requirements of the job.
  - `:sensory_requirement` - A description of any sensory requirements and levels necessary to function on the job, including hearing and vision. Defined terms such as those in O*net may be used, but note that there is no way to specify the level of ability as well as its nature when using a defined term.
  - `:skills` - A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is either claimed by a person, an organization or desired or required to fulfill a role or to work in an occupation.
  - `:special_commitments` - Any special commitments associated with this job posting. Valid entries include VeteranCommit, MilitarySpouseCommit, etc.
  - `:title` - The title of the job.
  - `:total_job_openings` - The number of positions open for this job posting. Use a positive integer. Do not use if the number of positions is unclear or not known.
  - `:valid_through` - The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours.
  - `:work_hours` - The typical working hours for this job (e.g. 1st shift, night shift, 8am-5pm).

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "JobPosting")
  end
end
