# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.Legislation do
  @moduledoc """
  A legal document such as an act, decree, bill, etc. (enforceable or not) or a component of a legal act (like an article).

  Helper for building a Schema.org [Legislation](https://schema.org/Legislation) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:jurisdiction) => String.t() | SEO.JSONLD.AdministrativeArea.t() | map(),
            optional(:legislation_amends) => SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_applies) => SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_changes) => SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_commences) => SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_consolidates) => SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_corrects) => SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_countersigned_by) =>
              SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:legislation_date) => Date.t() | String.t(),
            optional(:legislation_date_of_applicability) => Date.t() | String.t(),
            optional(:legislation_date_version) => Date.t() | String.t(),
            optional(:legislation_ensures_implementation_of) =>
              SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_identifier) => String.t() | URI.t(),
            optional(:legislation_jurisdiction) =>
              SEO.JSONLD.AdministrativeArea.t() | map() | String.t(),
            optional(:legislation_legal_force) => :in_force | :not_in_force | :partially_in_force,
            optional(:legislation_passed_by) =>
              SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:legislation_repeals) => SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_responsible) =>
              SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:legislation_transposes) => SEO.JSONLD.Legislation.t() | map(),
            optional(:legislation_type) => SEO.JSONLD.CategoryCode.t() | map() | String.t(),
            optional(:about) => SEO.JSONLD.Thing.t() | map(),
            optional(:abstract) => String.t(),
            optional(:access_mode) => String.t(),
            optional(:access_mode_sufficient) => SEO.JSONLD.ItemList.t() | map(),
            optional(:accessibility_api) => String.t(),
            optional(:accessibility_control) => String.t(),
            optional(:accessibility_feature) => String.t(),
            optional(:accessibility_hazard) => String.t(),
            optional(:accessibility_summary) => String.t(),
            optional(:accountable_person) => SEO.JSONLD.Person.t() | map(),
            optional(:acquire_license_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:aggregate_rating) => SEO.JSONLD.AggregateRating.t() | map(),
            optional(:alternative_headline) => String.t(),
            optional(:archived_at) => SEO.JSONLD.WebPage.t() | map() | URI.t() | String.t(),
            optional(:assesses) => String.t() | SEO.JSONLD.DefinedTerm.t() | map(),
            optional(:associated_media) => SEO.JSONLD.MediaObject.t() | map(),
            optional(:audience) => SEO.JSONLD.Audience.t() | map(),
            optional(:audio) =>
              SEO.JSONLD.Clip.t()
              | map()
              | SEO.JSONLD.MusicRecording.t()
              | SEO.JSONLD.AudioObject.t(),
            optional(:author) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:award) => String.t(),
            optional(:awards) => String.t(),
            optional(:character) => SEO.JSONLD.Person.t() | map(),
            optional(:citation) => SEO.JSONLD.CreativeWork.t() | map() | String.t(),
            optional(:comment) => SEO.JSONLD.Comment.t() | map(),
            optional(:comment_count) => integer(),
            optional(:conditions_of_access) => String.t(),
            optional(:content_location) => SEO.JSONLD.Place.t() | map(),
            optional(:content_rating) => String.t() | SEO.JSONLD.Rating.t() | map(),
            optional(:content_reference_time) => DateTime.t() | NaiveDateTime.t() | String.t(),
            optional(:contributor) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:copyright_holder) =>
              SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:copyright_notice) => String.t(),
            optional(:copyright_year) => number(),
            optional(:correction) =>
              SEO.JSONLD.CorrectionComment.t() | map() | String.t() | URI.t(),
            optional(:country_of_origin) => SEO.JSONLD.Country.t() | map(),
            optional(:creative_work_status) => SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
            optional(:creator) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:credit_text) => String.t(),
            optional(:date_created) => DateTime.t() | NaiveDateTime.t() | String.t() | Date.t(),
            optional(:date_modified) => DateTime.t() | NaiveDateTime.t() | String.t() | Date.t(),
            optional(:date_published) => Date.t() | String.t() | DateTime.t() | NaiveDateTime.t(),
            optional(:digital_source_type) =>
              :algorithmic_media_digital_source
              | :algorithmically_enhanced_digital_source
              | :composite_capture_digital_source
              | :composite_digital_source
              | :composite_synthetic_digital_source
              | :composite_with_trained_algorithmic_media_digital_source
              | :data_driven_media_digital_source
              | :digital_art_digital_source
              | :digital_capture_digital_source
              | :minor_human_edits_digital_source
              | :multi_frame_computational_capture_digital_source
              | :negative_film_digital_source
              | :positive_film_digital_source
              | :print_digital_source
              | :screen_capture_digital_source
              | :trained_algorithmic_media_digital_source
              | :virtual_recording_digital_source,
            optional(:discussion_url) => URI.t() | String.t(),
            optional(:display_location) => SEO.JSONLD.Place.t() | map(),
            optional(:edit_eidr) => String.t() | URI.t(),
            optional(:editor) => SEO.JSONLD.Person.t() | map(),
            optional(:educational_alignment) => SEO.JSONLD.AlignmentObject.t() | map(),
            optional(:educational_level) =>
              String.t() | URI.t() | SEO.JSONLD.DefinedTerm.t() | map(),
            optional(:educational_use) => SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
            optional(:encoding) => SEO.JSONLD.MediaObject.t() | map(),
            optional(:encoding_format) => String.t() | URI.t(),
            optional(:encodings) => SEO.JSONLD.MediaObject.t() | map(),
            optional(:example_of_work) => SEO.JSONLD.CreativeWork.t() | map(),
            optional(:expires) => Date.t() | String.t() | DateTime.t() | NaiveDateTime.t(),
            optional(:file_format) => String.t() | URI.t(),
            optional(:funder) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:funding) => SEO.JSONLD.Grant.t() | map(),
            optional(:genre) => String.t() | URI.t() | SEO.JSONLD.DefinedTerm.t() | map(),
            optional(:has_part) => SEO.JSONLD.CreativeWork.t() | map(),
            optional(:headline) => String.t(),
            optional(:in_language) => String.t() | SEO.JSONLD.Language.t() | map(),
            optional(:interaction_statistic) => SEO.JSONLD.InteractionCounter.t() | map(),
            optional(:interactivity_type) => String.t(),
            optional(:interpreted_as_claim) => SEO.JSONLD.Claim.t() | map(),
            optional(:is_accessible_for_free) => boolean(),
            optional(:is_based_on) =>
              SEO.JSONLD.CreativeWork.t() | map() | SEO.JSONLD.Product.t() | URI.t() | String.t(),
            optional(:is_based_on_url) =>
              SEO.JSONLD.CreativeWork.t() | map() | SEO.JSONLD.Product.t() | URI.t() | String.t(),
            optional(:is_family_friendly) => boolean(),
            optional(:is_part_of) => SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:keywords) => SEO.JSONLD.DefinedTerm.t() | map() | String.t() | URI.t(),
            optional(:learning_resource_type) => String.t() | SEO.JSONLD.DefinedTerm.t() | map(),
            optional(:license) => SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:location_created) => SEO.JSONLD.Place.t() | map(),
            optional(:main_entity) => SEO.JSONLD.Thing.t() | map(),
            optional(:maintainer) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:material) => String.t() | SEO.JSONLD.Product.t() | map() | URI.t(),
            optional(:material_extent) => SEO.JSONLD.QuantitativeValue.t() | map() | String.t(),
            optional(:mentions) => SEO.JSONLD.Thing.t() | map(),
            optional(:offers) => SEO.JSONLD.Offer.t() | map() | SEO.JSONLD.Demand.t(),
            optional(:pattern) => SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
            optional(:position) => String.t() | integer(),
            optional(:producer) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:provider) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:publication) => SEO.JSONLD.PublicationEvent.t() | map(),
            optional(:publisher) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:publisher_imprint) => SEO.JSONLD.Organization.t() | map(),
            optional(:publishing_principles) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:recorded_at) => SEO.JSONLD.Event.t() | map(),
            optional(:released_event) => SEO.JSONLD.PublicationEvent.t() | map(),
            optional(:review) => SEO.JSONLD.Review.t() | map(),
            optional(:reviews) => SEO.JSONLD.Review.t() | map(),
            optional(:schema_version) => String.t() | URI.t(),
            optional(:sd_date_published) => Date.t() | String.t(),
            optional(:sd_license) => URI.t() | String.t() | SEO.JSONLD.CreativeWork.t() | map(),
            optional(:sd_publisher) =>
              SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:size) =>
              SEO.JSONLD.DefinedTerm.t() | map() | SEO.JSONLD.QuantitativeValue.t() | String.t(),
            optional(:source_organization) => SEO.JSONLD.Organization.t() | map(),
            optional(:spatial) => SEO.JSONLD.Place.t() | map(),
            optional(:spatial_coverage) => SEO.JSONLD.Place.t() | map(),
            optional(:sponsor) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:teaches) => SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
            optional(:temporal) => String.t() | DateTime.t() | NaiveDateTime.t(),
            optional(:temporal_coverage) =>
              String.t() | URI.t() | DateTime.t() | NaiveDateTime.t(),
            optional(:text) => String.t(),
            optional(:thumbnail) => SEO.JSONLD.ImageObject.t() | map(),
            optional(:thumbnail_url) => URI.t() | String.t(),
            optional(:time_required) => Duration.t() | String.t(),
            optional(:translation_of_work) => SEO.JSONLD.CreativeWork.t() | map(),
            optional(:translator) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:typical_age_range) => String.t(),
            optional(:usage_info) => SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:version) => String.t() | number(),
            optional(:video) => SEO.JSONLD.VideoObject.t() | map() | SEO.JSONLD.Clip.t(),
            optional(:word_count) => integer(),
            optional(:work_example) => SEO.JSONLD.CreativeWork.t() | map(),
            optional(:work_translation) => SEO.JSONLD.CreativeWork.t() | map(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              jurisdiction: String.t() | SEO.JSONLD.AdministrativeArea.t() | map(),
              legislation_amends: SEO.JSONLD.Legislation.t() | map(),
              legislation_applies: SEO.JSONLD.Legislation.t() | map(),
              legislation_changes: SEO.JSONLD.Legislation.t() | map(),
              legislation_commences: SEO.JSONLD.Legislation.t() | map(),
              legislation_consolidates: SEO.JSONLD.Legislation.t() | map(),
              legislation_corrects: SEO.JSONLD.Legislation.t() | map(),
              legislation_countersigned_by:
                SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              legislation_date: Date.t() | String.t(),
              legislation_date_of_applicability: Date.t() | String.t(),
              legislation_date_version: Date.t() | String.t(),
              legislation_ensures_implementation_of: SEO.JSONLD.Legislation.t() | map(),
              legislation_identifier: String.t() | URI.t(),
              legislation_jurisdiction: SEO.JSONLD.AdministrativeArea.t() | map() | String.t(),
              legislation_legal_force: :in_force | :not_in_force | :partially_in_force,
              legislation_passed_by: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              legislation_repeals: SEO.JSONLD.Legislation.t() | map(),
              legislation_responsible:
                SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              legislation_transposes: SEO.JSONLD.Legislation.t() | map(),
              legislation_type: SEO.JSONLD.CategoryCode.t() | map() | String.t(),
              about: SEO.JSONLD.Thing.t() | map(),
              abstract: String.t(),
              access_mode: String.t(),
              access_mode_sufficient: SEO.JSONLD.ItemList.t() | map(),
              accessibility_api: String.t(),
              accessibility_control: String.t(),
              accessibility_feature: String.t(),
              accessibility_hazard: String.t(),
              accessibility_summary: String.t(),
              accountable_person: SEO.JSONLD.Person.t() | map(),
              acquire_license_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              aggregate_rating: SEO.JSONLD.AggregateRating.t() | map(),
              alternative_headline: String.t(),
              archived_at: SEO.JSONLD.WebPage.t() | map() | URI.t() | String.t(),
              assesses: String.t() | SEO.JSONLD.DefinedTerm.t() | map(),
              associated_media: SEO.JSONLD.MediaObject.t() | map(),
              audience: SEO.JSONLD.Audience.t() | map(),
              audio:
                SEO.JSONLD.Clip.t()
                | map()
                | SEO.JSONLD.MusicRecording.t()
                | SEO.JSONLD.AudioObject.t(),
              author: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              award: String.t(),
              awards: String.t(),
              character: SEO.JSONLD.Person.t() | map(),
              citation: SEO.JSONLD.CreativeWork.t() | map() | String.t(),
              comment: SEO.JSONLD.Comment.t() | map(),
              comment_count: integer(),
              conditions_of_access: String.t(),
              content_location: SEO.JSONLD.Place.t() | map(),
              content_rating: String.t() | SEO.JSONLD.Rating.t() | map(),
              content_reference_time: DateTime.t() | NaiveDateTime.t() | String.t(),
              contributor: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              copyright_holder: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              copyright_notice: String.t(),
              copyright_year: number(),
              correction: SEO.JSONLD.CorrectionComment.t() | map() | String.t() | URI.t(),
              country_of_origin: SEO.JSONLD.Country.t() | map(),
              creative_work_status: SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
              creator: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              credit_text: String.t(),
              date_created: DateTime.t() | NaiveDateTime.t() | String.t() | Date.t(),
              date_modified: DateTime.t() | NaiveDateTime.t() | String.t() | Date.t(),
              date_published: Date.t() | String.t() | DateTime.t() | NaiveDateTime.t(),
              digital_source_type:
                :algorithmic_media_digital_source
                | :algorithmically_enhanced_digital_source
                | :composite_capture_digital_source
                | :composite_digital_source
                | :composite_synthetic_digital_source
                | :composite_with_trained_algorithmic_media_digital_source
                | :data_driven_media_digital_source
                | :digital_art_digital_source
                | :digital_capture_digital_source
                | :minor_human_edits_digital_source
                | :multi_frame_computational_capture_digital_source
                | :negative_film_digital_source
                | :positive_film_digital_source
                | :print_digital_source
                | :screen_capture_digital_source
                | :trained_algorithmic_media_digital_source
                | :virtual_recording_digital_source,
              discussion_url: URI.t() | String.t(),
              display_location: SEO.JSONLD.Place.t() | map(),
              edit_eidr: String.t() | URI.t(),
              editor: SEO.JSONLD.Person.t() | map(),
              educational_alignment: SEO.JSONLD.AlignmentObject.t() | map(),
              educational_level: String.t() | URI.t() | SEO.JSONLD.DefinedTerm.t() | map(),
              educational_use: SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
              encoding: SEO.JSONLD.MediaObject.t() | map(),
              encoding_format: String.t() | URI.t(),
              encodings: SEO.JSONLD.MediaObject.t() | map(),
              example_of_work: SEO.JSONLD.CreativeWork.t() | map(),
              expires: Date.t() | String.t() | DateTime.t() | NaiveDateTime.t(),
              file_format: String.t() | URI.t(),
              funder: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              funding: SEO.JSONLD.Grant.t() | map(),
              genre: String.t() | URI.t() | SEO.JSONLD.DefinedTerm.t() | map(),
              has_part: SEO.JSONLD.CreativeWork.t() | map(),
              headline: String.t(),
              in_language: String.t() | SEO.JSONLD.Language.t() | map(),
              interaction_statistic: SEO.JSONLD.InteractionCounter.t() | map(),
              interactivity_type: String.t(),
              interpreted_as_claim: SEO.JSONLD.Claim.t() | map(),
              is_accessible_for_free: boolean(),
              is_based_on:
                SEO.JSONLD.CreativeWork.t()
                | map()
                | SEO.JSONLD.Product.t()
                | URI.t()
                | String.t(),
              is_based_on_url:
                SEO.JSONLD.CreativeWork.t()
                | map()
                | SEO.JSONLD.Product.t()
                | URI.t()
                | String.t(),
              is_family_friendly: boolean(),
              is_part_of: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              keywords: SEO.JSONLD.DefinedTerm.t() | map() | String.t() | URI.t(),
              learning_resource_type: String.t() | SEO.JSONLD.DefinedTerm.t() | map(),
              license: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              location_created: SEO.JSONLD.Place.t() | map(),
              main_entity: SEO.JSONLD.Thing.t() | map(),
              maintainer: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              material: String.t() | SEO.JSONLD.Product.t() | map() | URI.t(),
              material_extent: SEO.JSONLD.QuantitativeValue.t() | map() | String.t(),
              mentions: SEO.JSONLD.Thing.t() | map(),
              offers: SEO.JSONLD.Offer.t() | map() | SEO.JSONLD.Demand.t(),
              pattern: SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
              position: String.t() | integer(),
              producer: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              provider: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              publication: SEO.JSONLD.PublicationEvent.t() | map(),
              publisher: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              publisher_imprint: SEO.JSONLD.Organization.t() | map(),
              publishing_principles: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              recorded_at: SEO.JSONLD.Event.t() | map(),
              released_event: SEO.JSONLD.PublicationEvent.t() | map(),
              review: SEO.JSONLD.Review.t() | map(),
              reviews: SEO.JSONLD.Review.t() | map(),
              schema_version: String.t() | URI.t(),
              sd_date_published: Date.t() | String.t(),
              sd_license: URI.t() | String.t() | SEO.JSONLD.CreativeWork.t() | map(),
              sd_publisher: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              size:
                SEO.JSONLD.DefinedTerm.t() | map() | SEO.JSONLD.QuantitativeValue.t() | String.t(),
              source_organization: SEO.JSONLD.Organization.t() | map(),
              spatial: SEO.JSONLD.Place.t() | map(),
              spatial_coverage: SEO.JSONLD.Place.t() | map(),
              sponsor: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              teaches: SEO.JSONLD.DefinedTerm.t() | map() | String.t(),
              temporal: String.t() | DateTime.t() | NaiveDateTime.t(),
              temporal_coverage: String.t() | URI.t() | DateTime.t() | NaiveDateTime.t(),
              text: String.t(),
              thumbnail: SEO.JSONLD.ImageObject.t() | map(),
              thumbnail_url: URI.t() | String.t(),
              time_required: Duration.t() | String.t(),
              translation_of_work: SEO.JSONLD.CreativeWork.t() | map(),
              translator: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              typical_age_range: String.t(),
              usage_info: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              version: String.t() | number(),
              video: SEO.JSONLD.VideoObject.t() | map() | SEO.JSONLD.Clip.t(),
              word_count: integer(),
              work_example: SEO.JSONLD.CreativeWork.t() | map(),
              work_translation: SEO.JSONLD.CreativeWork.t() | map(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"Legislation"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{
    :digital_source_type => %{
      :algorithmic_media_digital_source => "https://schema.org/AlgorithmicMediaDigitalSource",
      :algorithmically_enhanced_digital_source =>
        "https://schema.org/AlgorithmicallyEnhancedDigitalSource",
      :composite_capture_digital_source => "https://schema.org/CompositeCaptureDigitalSource",
      :composite_digital_source => "https://schema.org/CompositeDigitalSource",
      :composite_synthetic_digital_source => "https://schema.org/CompositeSyntheticDigitalSource",
      :composite_with_trained_algorithmic_media_digital_source =>
        "https://schema.org/CompositeWithTrainedAlgorithmicMediaDigitalSource",
      :data_driven_media_digital_source => "https://schema.org/DataDrivenMediaDigitalSource",
      :digital_art_digital_source => "https://schema.org/DigitalArtDigitalSource",
      :digital_capture_digital_source => "https://schema.org/DigitalCaptureDigitalSource",
      :minor_human_edits_digital_source => "https://schema.org/MinorHumanEditsDigitalSource",
      :multi_frame_computational_capture_digital_source =>
        "https://schema.org/MultiFrameComputationalCaptureDigitalSource",
      :negative_film_digital_source => "https://schema.org/NegativeFilmDigitalSource",
      :positive_film_digital_source => "https://schema.org/PositiveFilmDigitalSource",
      :print_digital_source => "https://schema.org/PrintDigitalSource",
      :screen_capture_digital_source => "https://schema.org/ScreenCaptureDigitalSource",
      :trained_algorithmic_media_digital_source =>
        "https://schema.org/TrainedAlgorithmicMediaDigitalSource",
      :virtual_recording_digital_source => "https://schema.org/VirtualRecordingDigitalSource"
    },
    :legislation_legal_force => %{
      :in_force => "https://schema.org/InForce",
      :not_in_force => "https://schema.org/NotInForce",
      :partially_in_force => "https://schema.org/PartiallyInForce"
    },
    :size => %{}
  }
  @key_map %{
    :access_mode => "accessMode",
    :access_mode_sufficient => "accessModeSufficient",
    :accessibility_api => "accessibilityAPI",
    :accessibility_control => "accessibilityControl",
    :accessibility_feature => "accessibilityFeature",
    :accessibility_hazard => "accessibilityHazard",
    :accessibility_summary => "accessibilitySummary",
    :accountable_person => "accountablePerson",
    :acquire_license_page => "acquireLicensePage",
    :additional_type => "additionalType",
    :aggregate_rating => "aggregateRating",
    :alternate_name => "alternateName",
    :alternative_headline => "alternativeHeadline",
    :archived_at => "archivedAt",
    :associated_media => "associatedMedia",
    :comment_count => "commentCount",
    :conditions_of_access => "conditionsOfAccess",
    :content_location => "contentLocation",
    :content_rating => "contentRating",
    :content_reference_time => "contentReferenceTime",
    :copyright_holder => "copyrightHolder",
    :copyright_notice => "copyrightNotice",
    :copyright_year => "copyrightYear",
    :country_of_origin => "countryOfOrigin",
    :creative_work_status => "creativeWorkStatus",
    :credit_text => "creditText",
    :date_created => "dateCreated",
    :date_modified => "dateModified",
    :date_published => "datePublished",
    :digital_source_type => "digitalSourceType",
    :disambiguating_description => "disambiguatingDescription",
    :discussion_url => "discussionUrl",
    :display_location => "displayLocation",
    :edit_eidr => "editEIDR",
    :educational_alignment => "educationalAlignment",
    :educational_level => "educationalLevel",
    :educational_use => "educationalUse",
    :encoding_format => "encodingFormat",
    :example_of_work => "exampleOfWork",
    :file_format => "fileFormat",
    :has_part => "hasPart",
    :in_language => "inLanguage",
    :interaction_statistic => "interactionStatistic",
    :interactivity_type => "interactivityType",
    :interpreted_as_claim => "interpretedAsClaim",
    :is_accessible_for_free => "isAccessibleForFree",
    :is_based_on => "isBasedOn",
    :is_based_on_url => "isBasedOnUrl",
    :is_family_friendly => "isFamilyFriendly",
    :is_part_of => "isPartOf",
    :learning_resource_type => "learningResourceType",
    :legislation_amends => "legislationAmends",
    :legislation_applies => "legislationApplies",
    :legislation_changes => "legislationChanges",
    :legislation_commences => "legislationCommences",
    :legislation_consolidates => "legislationConsolidates",
    :legislation_corrects => "legislationCorrects",
    :legislation_countersigned_by => "legislationCountersignedBy",
    :legislation_date => "legislationDate",
    :legislation_date_of_applicability => "legislationDateOfApplicability",
    :legislation_date_version => "legislationDateVersion",
    :legislation_ensures_implementation_of => "legislationEnsuresImplementationOf",
    :legislation_identifier => "legislationIdentifier",
    :legislation_jurisdiction => "legislationJurisdiction",
    :legislation_legal_force => "legislationLegalForce",
    :legislation_passed_by => "legislationPassedBy",
    :legislation_repeals => "legislationRepeals",
    :legislation_responsible => "legislationResponsible",
    :legislation_transposes => "legislationTransposes",
    :legislation_type => "legislationType",
    :location_created => "locationCreated",
    :main_entity => "mainEntity",
    :main_entity_of_page => "mainEntityOfPage",
    :material_extent => "materialExtent",
    :potential_action => "potentialAction",
    :publisher_imprint => "publisherImprint",
    :publishing_principles => "publishingPrinciples",
    :recorded_at => "recordedAt",
    :released_event => "releasedEvent",
    :same_as => "sameAs",
    :schema_version => "schemaVersion",
    :sd_date_published => "sdDatePublished",
    :sd_license => "sdLicense",
    :sd_publisher => "sdPublisher",
    :source_organization => "sourceOrganization",
    :spatial_coverage => "spatialCoverage",
    :subject_of => "subjectOf",
    :temporal_coverage => "temporalCoverage",
    :thumbnail_url => "thumbnailUrl",
    :time_required => "timeRequired",
    :translation_of_work => "translationOfWork",
    :typical_age_range => "typicalAgeRange",
    :usage_info => "usageInfo",
    :word_count => "wordCount",
    :work_example => "workExample",
    :work_translation => "workTranslation"
  }

  @doc """
  Build a Legislation JSON-LD map.

  ## Fields

  - `:jurisdiction` - Indicates a legal jurisdiction, e.g. of some legislation, or where some government service is based.
  - `:legislation_amends` - Another legislation that this legislation amends, introducing legal changes.
  - `:legislation_applies` - Indicates that this legislation (or part of a legislation) somehow transfers another legislation in a different legislative context. This is an informative link, and it has no legal value. For legally-binding links of transposition, use the legislationTransposes property. For example an informative consolidated law of a European Union's member state "applies" the consolidated version of the European Directive implemented in it.
  - `:legislation_changes` - Another legislation that this legislation changes. This encompasses the notions of amendment, replacement, correction, repeal, or other types of change. This may be a direct change (textual or non-textual amendment) or a consequential or indirect change. The property is to be used to express the existence of a change relationship between two acts rather than the existence of a consolidated version of the text that shows the result of the change. For consolidation relationships, use the legislationConsolidates property.
  - `:legislation_commences` - Another legislation that this one sets into force.
  - `:legislation_consolidates` - Indicates another legislation taken into account in this consolidated legislation (which is usually the product of an editorial process that revises the legislation). This property should be used multiple times to refer to both the original version or the previous consolidated version, and to the legislations making the change.
  - `:legislation_corrects` - Another legislation in which this one introduces textual changes, like correction of spelling mistakes, with no legal impact (for modifications that have legal impact, use legislationAmends).
  - `:legislation_countersigned_by` - The person or organization that countersigned the legislation. Depending on the legal context, a countersignature can indicate that the signed authority undertakes to assume responsibility for texts emanating from a person who is inviolable and irresponsible, (for example a King, Grand Duc or President), or that the authority is in charge of the implementation of the text.
  - `:legislation_date` - The date of adoption or signature of the legislation. This is the date at which the text is officially aknowledged to be a legislation, even though it might not even be published or in force.
  - `:legislation_date_of_applicability` - The date at which the Legislation becomes applicable. This can sometimes be distinct from the date of entry into force : a text may come in force today, and state it will become applicable in 3 months.
  - `:legislation_date_version` - The point-in-time at which the provided description of the legislation is valid (e.g.: when looking at the law on the 2016-04-07 (= dateVersion), I get the consolidation of 2015-04-12 of the "National Insurance Contributions Act 2015")
  - `:legislation_ensures_implementation_of` - Indicates that this Legislation ensures the implementation of another Legislation, for example by modifying national legislations so that they do not contradict to an EU regulation or decision. This implies a legal meaning. Transpositions of EU Directive should be captured with legislationTransposes.
  - `:legislation_identifier` - An identifier for the legislation. This can be either a string-based identifier, like the CELEX at EU level or the NOR in France, or a web-based, URL/URI identifier, like an ELI (European Legislation Identifier) or an URN-Lex.
  - `:legislation_jurisdiction` - The jurisdiction from which the legislation originates.
  - `:legislation_legal_force` - Whether the legislation is currently in force, not in force, or partially in force. One of: `:in_force`, `:not_in_force`, `:partially_in_force`.
  - `:legislation_passed_by` - The person or organization that originally passed or made the law: typically parliament (for primary legislation) or government (for secondary legislation). This indicates the "legal author" of the law, as opposed to its physical author.
  - `:legislation_repeals` - Another legislation that this legislation repeals (cancels, abrogates).
  - `:legislation_responsible` - An individual or organization that has some kind of responsibility for the legislation. Typically the ministry who is/was in charge of elaborating the legislation, or the adressee for potential questions about the legislation once it is published.
  - `:legislation_transposes` - Indicates that this legislation (or part of legislation) fulfills the objectives set by another legislation, by passing appropriate implementation measures. Typically, some legislations of European Union's member states or regions transpose European Directives. This indicates a legally binding link between the 2 legislations.
  - `:legislation_type` - The type of the legislation. Examples of values are "law", "act", "directive", "decree", "regulation", "statutory instrument", "loi organique", "règlement grand-ducal", etc., depending on the country.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.CreativeWork`
  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "Legislation")
  end
end
