# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.NutritionInformation do
  @moduledoc """
  Nutritional information about the recipe.

  Helper for building a Schema.org [NutritionInformation](https://schema.org/NutritionInformation) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:calories) => map(),
            optional(:carbohydrate_content) => map(),
            optional(:cholesterol_content) => map(),
            optional(:fat_content) => map(),
            optional(:fiber_content) => map(),
            optional(:protein_content) => map(),
            optional(:saturated_fat_content) => map(),
            optional(:serving_size) => String.t(),
            optional(:sodium_content) => map(),
            optional(:sugar_content) => map(),
            optional(:trans_fat_content) => map(),
            optional(:unsaturated_fat_content) => map(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              calories: map(),
              carbohydrate_content: map(),
              cholesterol_content: map(),
              fat_content: map(),
              fiber_content: map(),
              protein_content: map(),
              saturated_fat_content: map(),
              serving_size: String.t(),
              sodium_content: map(),
              sugar_content: map(),
              trans_fat_content: map(),
              unsaturated_fat_content: map(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"NutritionInformation"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{}
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :carbohydrate_content => "carbohydrateContent",
    :cholesterol_content => "cholesterolContent",
    :disambiguating_description => "disambiguatingDescription",
    :fat_content => "fatContent",
    :fiber_content => "fiberContent",
    :main_entity_of_page => "mainEntityOfPage",
    :potential_action => "potentialAction",
    :protein_content => "proteinContent",
    :same_as => "sameAs",
    :saturated_fat_content => "saturatedFatContent",
    :serving_size => "servingSize",
    :sodium_content => "sodiumContent",
    :subject_of => "subjectOf",
    :sugar_content => "sugarContent",
    :trans_fat_content => "transFatContent",
    :unsaturated_fat_content => "unsaturatedFatContent"
  }

  @doc """
  Build a NutritionInformation JSON-LD map.

  ## Fields

  - `:calories` - The number of calories.
  - `:carbohydrate_content` - The number of grams of carbohydrates.
  - `:cholesterol_content` - The number of milligrams of cholesterol.
  - `:fat_content` - The number of grams of fat.
  - `:fiber_content` - The number of grams of fiber.
  - `:protein_content` - The number of grams of protein.
  - `:saturated_fat_content` - The number of grams of saturated fat.
  - `:serving_size` - The serving size, in terms of the number of volume or mass.
  - `:sodium_content` - The number of milligrams of sodium.
  - `:sugar_content` - The number of grams of sugar.
  - `:trans_fat_content` - The number of grams of trans fat.
  - `:unsaturated_fat_content` - The number of grams of unsaturated fat.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "NutritionInformation")
  end
end
