# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.Place do
  @moduledoc """
  Entities that have a somewhat fixed, physical extension.

  Helper for building a Schema.org [Place](https://schema.org/Place) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:additional_property) => SEO.JSONLD.PropertyValue.t() | map(),
            optional(:address) => String.t() | SEO.JSONLD.PostalAddress.t() | map(),
            optional(:aggregate_rating) => SEO.JSONLD.AggregateRating.t() | map(),
            optional(:amenity_feature) => SEO.JSONLD.LocationFeatureSpecification.t() | map(),
            optional(:branch_code) => String.t(),
            optional(:contained_in) => SEO.JSONLD.Place.t() | map(),
            optional(:contained_in_place) => SEO.JSONLD.Place.t() | map(),
            optional(:contains_place) => SEO.JSONLD.Place.t() | map(),
            optional(:event) => SEO.JSONLD.Event.t() | map(),
            optional(:events) => SEO.JSONLD.Event.t() | map(),
            optional(:fax_number) => String.t(),
            optional(:geo) => SEO.JSONLD.GeoShape.t() | map() | SEO.JSONLD.GeoCoordinates.t(),
            optional(:geo_contains) =>
              SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
            optional(:geo_covered_by) =>
              SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
            optional(:geo_covers) =>
              SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
            optional(:geo_crosses) =>
              SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
            optional(:geo_disjoint) =>
              SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
            optional(:geo_equals) =>
              SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
            optional(:geo_intersects) =>
              SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
            optional(:geo_overlaps) =>
              SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
            optional(:geo_touches) =>
              SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
            optional(:geo_within) =>
              SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
            optional(:global_location_number) => String.t(),
            optional(:has_certification) => SEO.JSONLD.Certification.t() | map(),
            optional(:has_drive_through_service) => boolean(),
            optional(:has_gs1_digital_link) => URI.t() | String.t(),
            optional(:has_map) => URI.t() | String.t() | SEO.JSONLD.Map.t() | map(),
            optional(:is_accessible_for_free) => boolean(),
            optional(:isic_v4) => String.t(),
            optional(:keywords) => SEO.JSONLD.DefinedTerm.t() | map() | String.t() | URI.t(),
            optional(:latitude) => String.t() | number(),
            optional(:logo) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:longitude) => String.t() | number(),
            optional(:map) => URI.t() | String.t(),
            optional(:maps) => URI.t() | String.t(),
            optional(:maximum_attendee_capacity) => integer(),
            optional(:opening_hours_specification) =>
              SEO.JSONLD.OpeningHoursSpecification.t() | map(),
            optional(:photo) => SEO.JSONLD.Photograph.t() | map() | SEO.JSONLD.ImageObject.t(),
            optional(:photos) => SEO.JSONLD.Photograph.t() | map() | SEO.JSONLD.ImageObject.t(),
            optional(:public_access) => boolean(),
            optional(:review) => SEO.JSONLD.Review.t() | map(),
            optional(:reviews) => SEO.JSONLD.Review.t() | map(),
            optional(:slogan) => String.t(),
            optional(:smoking_allowed) => boolean(),
            optional(:special_opening_hours_specification) =>
              SEO.JSONLD.OpeningHoursSpecification.t() | map(),
            optional(:telephone) => String.t(),
            optional(:tour_booking_page) => URI.t() | String.t(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              additional_property: SEO.JSONLD.PropertyValue.t() | map(),
              address: String.t() | SEO.JSONLD.PostalAddress.t() | map(),
              aggregate_rating: SEO.JSONLD.AggregateRating.t() | map(),
              amenity_feature: SEO.JSONLD.LocationFeatureSpecification.t() | map(),
              branch_code: String.t(),
              contained_in: SEO.JSONLD.Place.t() | map(),
              contained_in_place: SEO.JSONLD.Place.t() | map(),
              contains_place: SEO.JSONLD.Place.t() | map(),
              event: SEO.JSONLD.Event.t() | map(),
              events: SEO.JSONLD.Event.t() | map(),
              fax_number: String.t(),
              geo: SEO.JSONLD.GeoShape.t() | map() | SEO.JSONLD.GeoCoordinates.t(),
              geo_contains: SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
              geo_covered_by: SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
              geo_covers: SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
              geo_crosses: SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
              geo_disjoint: SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
              geo_equals: SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
              geo_intersects: SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
              geo_overlaps: SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
              geo_touches: SEO.JSONLD.Place.t() | map() | SEO.JSONLD.GeospatialGeometry.t(),
              geo_within: SEO.JSONLD.GeospatialGeometry.t() | map() | SEO.JSONLD.Place.t(),
              global_location_number: String.t(),
              has_certification: SEO.JSONLD.Certification.t() | map(),
              has_drive_through_service: boolean(),
              has_gs1_digital_link: URI.t() | String.t(),
              has_map: URI.t() | String.t() | SEO.JSONLD.Map.t() | map(),
              is_accessible_for_free: boolean(),
              isic_v4: String.t(),
              keywords: SEO.JSONLD.DefinedTerm.t() | map() | String.t() | URI.t(),
              latitude: String.t() | number(),
              logo: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              longitude: String.t() | number(),
              map: URI.t() | String.t(),
              maps: URI.t() | String.t(),
              maximum_attendee_capacity: integer(),
              opening_hours_specification: SEO.JSONLD.OpeningHoursSpecification.t() | map(),
              photo: SEO.JSONLD.Photograph.t() | map() | SEO.JSONLD.ImageObject.t(),
              photos: SEO.JSONLD.Photograph.t() | map() | SEO.JSONLD.ImageObject.t(),
              public_access: boolean(),
              review: SEO.JSONLD.Review.t() | map(),
              reviews: SEO.JSONLD.Review.t() | map(),
              slogan: String.t(),
              smoking_allowed: boolean(),
              special_opening_hours_specification:
                SEO.JSONLD.OpeningHoursSpecification.t() | map(),
              telephone: String.t(),
              tour_booking_page: URI.t() | String.t(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"Place"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{}
  @key_map %{
    :additional_property => "additionalProperty",
    :additional_type => "additionalType",
    :aggregate_rating => "aggregateRating",
    :alternate_name => "alternateName",
    :amenity_feature => "amenityFeature",
    :branch_code => "branchCode",
    :contained_in => "containedIn",
    :contained_in_place => "containedInPlace",
    :contains_place => "containsPlace",
    :disambiguating_description => "disambiguatingDescription",
    :fax_number => "faxNumber",
    :geo_contains => "geoContains",
    :geo_covered_by => "geoCoveredBy",
    :geo_covers => "geoCovers",
    :geo_crosses => "geoCrosses",
    :geo_disjoint => "geoDisjoint",
    :geo_equals => "geoEquals",
    :geo_intersects => "geoIntersects",
    :geo_overlaps => "geoOverlaps",
    :geo_touches => "geoTouches",
    :geo_within => "geoWithin",
    :global_location_number => "globalLocationNumber",
    :has_certification => "hasCertification",
    :has_drive_through_service => "hasDriveThroughService",
    :has_gs1_digital_link => "hasGS1DigitalLink",
    :has_map => "hasMap",
    :is_accessible_for_free => "isAccessibleForFree",
    :isic_v4 => "isicV4",
    :main_entity_of_page => "mainEntityOfPage",
    :maximum_attendee_capacity => "maximumAttendeeCapacity",
    :opening_hours_specification => "openingHoursSpecification",
    :potential_action => "potentialAction",
    :public_access => "publicAccess",
    :same_as => "sameAs",
    :smoking_allowed => "smokingAllowed",
    :special_opening_hours_specification => "specialOpeningHoursSpecification",
    :subject_of => "subjectOf",
    :tour_booking_page => "tourBookingPage"
  }

  @doc """
  Build a Place JSON-LD map.

  ## Fields

  - `:additional_property` - A property-value pair representing an additional characteristic of the entity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.

  Note: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.
  - `:address` - Physical address of the item.
  - `:aggregate_rating` - The overall rating, based on a collection of reviews or ratings, of the item.
  - `:amenity_feature` - An amenity feature (e.g. a characteristic or service) of the Accommodation. This generic property does not make a statement about whether the feature is included in an offer for the main accommodation or available at extra costs.
  - `:branch_code` - A short textual code (also called "store code") that uniquely identifies a place of business. The code is typically assigned by the parentOrganization and used in structured URLs.

  For example, in the URL http://www.starbucks.co.uk/store-locator/etc/detail/3047 the code "3047" is a branchCode for a particular branch.
  - `:contained_in` - The basic containment relation between a place and one that contains it.
  - `:contained_in_place` - The basic containment relation between a place and one that contains it.
  - `:contains_place` - The basic containment relation between a place and another that it contains.
  - `:event` - Upcoming or past event associated with this place, organization, or action.
  - `:events` - Upcoming or past events associated with this place or organization.
  - `:fax_number` - The fax number.
  - `:geo` - The geo coordinates of the place.
  - `:geo_contains` - Represents a relationship between two geometries (or the places they represent), relating a containing geometry to a contained geometry. "a contains b iff no points of b lie in the exterior of a, and at least one point of the interior of b lies in the interior of a". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).
  - `:geo_covered_by` - Represents a relationship between two geometries (or the places they represent), relating a geometry to another that covers it. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).
  - `:geo_covers` - Represents a relationship between two geometries (or the places they represent), relating a covering geometry to a covered geometry. "Every point of b is a point of (the interior or boundary of) a". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).
  - `:geo_crosses` - Represents a relationship between two geometries (or the places they represent), relating a geometry to another that crosses it: "a crosses b: they have some but not all interior points in common, and the dimension of the intersection is less than that of at least one of them". As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).
  - `:geo_disjoint` - Represents spatial relations in which two geometries (or the places they represent) are topologically disjoint: "they have no point in common. They form a set of disconnected geometries." (A symmetric relationship, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).)
  - `:geo_equals` - Represents spatial relations in which two geometries (or the places they represent) are topologically equal, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM). "Two geometries are topologically equal if their interiors intersect and no part of the interior or boundary of one geometry intersects the exterior of the other" (a symmetric relationship).
  - `:geo_intersects` - Represents spatial relations in which two geometries (or the places they represent) have at least one point in common. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).
  - `:geo_overlaps` - Represents a relationship between two geometries (or the places they represent), relating a geometry to another that geospatially overlaps it, i.e. they have some but not all points in common. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).
  - `:geo_touches` - Represents spatial relations in which two geometries (or the places they represent) touch: "they have at least one boundary point in common, but no interior points." (A symmetric relationship, as defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).)
  - `:geo_within` - Represents a relationship between two geometries (or the places they represent), relating a geometry to one that contains it, i.e. it is inside (i.e. within) its interior. As defined in [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM).
  - `:global_location_number` - The [Global Location Number](http://www.gs1.org/gln) (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.
  - `:has_certification` - Certification information about a product, organization, service, place, or person.
  - `:has_drive_through_service` - Indicates whether some facility (e.g. `SEO.JSONLD.FoodEstablishment`, `SEO.JSONLD.CovidTestingFacility`) offers a service that can be used by driving through in a car. In the case of `SEO.JSONLD.CovidTestingFacility` such facilities could potentially help with social distancing from other potentially-infected users.
  - `:has_gs1_digital_link` - The GS1 digital link associated with the object. This URL should conform to the particular requirements of digital links. The link should only contain the Application Identifiers (AIs) that are relevant for the entity being annotated, for instance a `SEO.JSONLD.Product` or an `SEO.JSONLD.Organization`, and for the correct granularity. In particular, for products:A Digital Link that contains a serial number (AI 21) should only be present on instances of `SEO.JSONLD.IndividualProduct`A Digital Link that contains a lot number (AI 10) should be annotated as `SEO.JSONLD.SomeProducts` if only products from that lot are sold, or `SEO.JSONLD.IndividualProduct` if there is only a specific product.A Digital Link that contains a global model number (AI 8013) should be attached to a `SEO.JSONLD.Product` or a `SEO.JSONLD.ProductModel`. Other item types should be adapted similarly.
  - `:has_map` - A URL to a map of the place.
  - `:is_accessible_for_free` - A flag to signal that the item, event, or place is accessible for free.
  - `:isic_v4` - The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.
  - `:keywords` - Keywords or tags used to describe some item. Multiple textual entries in a keywords list are typically delimited by commas, or by repeating the property.
  - `:latitude` - The latitude of a location. For example ```37.42242``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).
  - `:logo` - An associated logo.
  - `:longitude` - The longitude of a location. For example ```-122.08585``` ([WGS 84](https://en.wikipedia.org/wiki/World_Geodetic_System)).
  - `:map` - A URL to a map of the place.
  - `:maps` - A URL to a map of the place.
  - `:maximum_attendee_capacity` - The total number of individuals that may attend an event or venue.
  - `:opening_hours_specification` - The opening hours of a certain place.
  - `:photo` - A photograph of this place.
  - `:photos` - Photographs of this place.
  - `:public_access` - A flag to signal that the `SEO.JSONLD.Place` is open to public visitors. If this property is omitted there is no assumed default boolean value.
  - `:review` - A review of the item.
  - `:reviews` - Review of the item.
  - `:slogan` - A slogan or motto associated with the item.
  - `:smoking_allowed` - Indicates whether it is allowed to smoke in the place, e.g. in the restaurant, hotel or hotel room.
  - `:special_opening_hours_specification` - The special opening hours of a certain place.

  Use this to explicitly override general opening hours brought in scope by `openingHoursSpecification` or `openingHours`.
  - `:telephone` - The telephone number.
  - `:tour_booking_page` - A page providing information on how to book a tour of some `SEO.JSONLD.Place`, such as an `SEO.JSONLD.Accommodation` or `SEO.JSONLD.ApartmentComplex` in a real estate setting, as well as other kinds of tours as appropriate.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "Place")
  end
end
