# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.RentalCarReservation do
  @moduledoc """
  A reservation for a rental car.

  Note: This type is for information about actual reservations, e.g. in confirmation emails or HTML pages with individual confirmations of reservations.

  Helper for building a Schema.org [RentalCarReservation](https://schema.org/RentalCarReservation) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:dropoff_location) => SEO.JSONLD.Place.t() | map(),
            optional(:dropoff_time) => DateTime.t() | NaiveDateTime.t() | String.t(),
            optional(:pickup_location) => SEO.JSONLD.Place.t() | map(),
            optional(:pickup_time) => DateTime.t() | NaiveDateTime.t() | String.t(),
            optional(:booking_agent) =>
              SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:booking_time) => DateTime.t() | NaiveDateTime.t() | String.t(),
            optional(:broker) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:modified_time) => DateTime.t() | NaiveDateTime.t() | String.t(),
            optional(:price_currency) => String.t(),
            optional(:program_membership_used) => SEO.JSONLD.ProgramMembership.t() | map(),
            optional(:provider) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:reservation_for) => SEO.JSONLD.Thing.t() | map(),
            optional(:reservation_id) => String.t(),
            optional(:reservation_status) =>
              :reservation_cancelled
              | :reservation_confirmed
              | :reservation_hold
              | :reservation_pending,
            optional(:reserved_ticket) => SEO.JSONLD.Ticket.t() | map(),
            optional(:total_price) =>
              SEO.JSONLD.PriceSpecification.t() | map() | String.t() | number(),
            optional(:under_name) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              dropoff_location: SEO.JSONLD.Place.t() | map(),
              dropoff_time: DateTime.t() | NaiveDateTime.t() | String.t(),
              pickup_location: SEO.JSONLD.Place.t() | map(),
              pickup_time: DateTime.t() | NaiveDateTime.t() | String.t(),
              booking_agent: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              booking_time: DateTime.t() | NaiveDateTime.t() | String.t(),
              broker: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              modified_time: DateTime.t() | NaiveDateTime.t() | String.t(),
              price_currency: String.t(),
              program_membership_used: SEO.JSONLD.ProgramMembership.t() | map(),
              provider: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              reservation_for: SEO.JSONLD.Thing.t() | map(),
              reservation_id: String.t(),
              reservation_status:
                :reservation_cancelled
                | :reservation_confirmed
                | :reservation_hold
                | :reservation_pending,
              reserved_ticket: SEO.JSONLD.Ticket.t() | map(),
              total_price: SEO.JSONLD.PriceSpecification.t() | map() | String.t() | number(),
              under_name: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"RentalCarReservation"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{
    :reservation_status => %{
      :reservation_cancelled => "https://schema.org/ReservationCancelled",
      :reservation_confirmed => "https://schema.org/ReservationConfirmed",
      :reservation_hold => "https://schema.org/ReservationHold",
      :reservation_pending => "https://schema.org/ReservationPending"
    }
  }
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :booking_agent => "bookingAgent",
    :booking_time => "bookingTime",
    :disambiguating_description => "disambiguatingDescription",
    :dropoff_location => "dropoffLocation",
    :dropoff_time => "dropoffTime",
    :main_entity_of_page => "mainEntityOfPage",
    :modified_time => "modifiedTime",
    :pickup_location => "pickupLocation",
    :pickup_time => "pickupTime",
    :potential_action => "potentialAction",
    :price_currency => "priceCurrency",
    :program_membership_used => "programMembershipUsed",
    :reservation_for => "reservationFor",
    :reservation_id => "reservationId",
    :reservation_status => "reservationStatus",
    :reserved_ticket => "reservedTicket",
    :same_as => "sameAs",
    :subject_of => "subjectOf",
    :total_price => "totalPrice",
    :under_name => "underName"
  }

  @doc """
  Build a RentalCarReservation JSON-LD map.

  ## Fields

  - `:dropoff_location` - Where a rental car can be dropped off.
  - `:dropoff_time` - When a rental car can be dropped off.
  - `:pickup_location` - Where a taxi will pick up a passenger or a rental car can be picked up.
  - `:pickup_time` - When a taxi will pick up a passenger or a rental car can be picked up.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Reservation`
  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "RentalCarReservation")
  end
end
