# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.RsvpAction do
  @moduledoc """
  The act of notifying an event organizer as to whether you expect to attend the event.

  Helper for building a Schema.org [RsvpAction](https://schema.org/RsvpAction) JSON-LD structure.
  ## Action inputs and outputs

  This type descends from `SEO.JSONLD.Action`, so `build/1` recognizes
  two pseudo-fields that expand into Schema.org's hyphenated
  `<property>-input` / `<property>-output` shorthand (see
  [Schema.org Actions, Part 4](https://schema.org/docs/actions.html)):

  - `:inputs` — a keyword list of `{property, constraints}` entries
  - `:outputs` — likewise, for `<property>-output` annotations

  Constraints are passed to `SEO.JSONLD.Actions.input_spec/1`.

  """

  @type attrs ::
          %{
            optional(:additional_number_of_guests) => number(),
            optional(:comment) => SEO.JSONLD.Comment.t() | map(),
            optional(:rsvp_response) =>
              :rsvp_response_maybe | :rsvp_response_no | :rsvp_response_yes,
            optional(:event) => SEO.JSONLD.Event.t() | map(),
            optional(:about) => SEO.JSONLD.Thing.t() | map(),
            optional(:in_language) => String.t() | SEO.JSONLD.Language.t() | map(),
            optional(:language) => SEO.JSONLD.Language.t() | map(),
            optional(:recipient) =>
              SEO.JSONLD.Organization.t()
              | map()
              | SEO.JSONLD.Person.t()
              | SEO.JSONLD.ContactPoint.t()
              | SEO.JSONLD.Audience.t(),
            optional(:action_process) => SEO.JSONLD.HowTo.t() | map(),
            optional(:action_status) =>
              :active_action_status
              | :completed_action_status
              | :failed_action_status
              | :potential_action_status,
            optional(:agent) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:end_time) => DateTime.t() | NaiveDateTime.t() | String.t() | Time.t(),
            optional(:error) => SEO.JSONLD.Thing.t() | map(),
            optional(:instrument) => SEO.JSONLD.Thing.t() | map(),
            optional(:location) =>
              String.t()
              | SEO.JSONLD.PostalAddress.t()
              | map()
              | SEO.JSONLD.VirtualLocation.t()
              | SEO.JSONLD.Place.t(),
            optional(:object) => SEO.JSONLD.Thing.t() | map(),
            optional(:participant) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:provider) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:result) => SEO.JSONLD.Thing.t() | map(),
            optional(:start_time) => DateTime.t() | NaiveDateTime.t() | String.t() | Time.t(),
            optional(:target) => URI.t() | String.t() | SEO.JSONLD.EntryPoint.t() | map(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              additional_number_of_guests: number(),
              comment: SEO.JSONLD.Comment.t() | map(),
              rsvp_response: :rsvp_response_maybe | :rsvp_response_no | :rsvp_response_yes,
              event: SEO.JSONLD.Event.t() | map(),
              about: SEO.JSONLD.Thing.t() | map(),
              in_language: String.t() | SEO.JSONLD.Language.t() | map(),
              language: SEO.JSONLD.Language.t() | map(),
              recipient:
                SEO.JSONLD.Organization.t()
                | map()
                | SEO.JSONLD.Person.t()
                | SEO.JSONLD.ContactPoint.t()
                | SEO.JSONLD.Audience.t(),
              action_process: SEO.JSONLD.HowTo.t() | map(),
              action_status:
                :active_action_status
                | :completed_action_status
                | :failed_action_status
                | :potential_action_status,
              agent: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              end_time: DateTime.t() | NaiveDateTime.t() | String.t() | Time.t(),
              error: SEO.JSONLD.Thing.t() | map(),
              instrument: SEO.JSONLD.Thing.t() | map(),
              location:
                String.t()
                | SEO.JSONLD.PostalAddress.t()
                | map()
                | SEO.JSONLD.VirtualLocation.t()
                | SEO.JSONLD.Place.t(),
              object: SEO.JSONLD.Thing.t() | map(),
              participant: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              provider: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              result: SEO.JSONLD.Thing.t() | map(),
              start_time: DateTime.t() | NaiveDateTime.t() | String.t() | Time.t(),
              target: URI.t() | String.t() | SEO.JSONLD.EntryPoint.t() | map(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"RsvpAction"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{
    :action_status => %{
      :active_action_status => "https://schema.org/ActiveActionStatus",
      :completed_action_status => "https://schema.org/CompletedActionStatus",
      :failed_action_status => "https://schema.org/FailedActionStatus",
      :potential_action_status => "https://schema.org/PotentialActionStatus"
    },
    :rsvp_response => %{
      :rsvp_response_maybe => "https://schema.org/RsvpResponseMaybe",
      :rsvp_response_no => "https://schema.org/RsvpResponseNo",
      :rsvp_response_yes => "https://schema.org/RsvpResponseYes"
    }
  }
  @key_map %{
    :action_process => "actionProcess",
    :action_status => "actionStatus",
    :additional_number_of_guests => "additionalNumberOfGuests",
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :disambiguating_description => "disambiguatingDescription",
    :end_time => "endTime",
    :in_language => "inLanguage",
    :main_entity_of_page => "mainEntityOfPage",
    :potential_action => "potentialAction",
    :rsvp_response => "rsvpResponse",
    :same_as => "sameAs",
    :start_time => "startTime",
    :subject_of => "subjectOf"
  }

  @doc """
  Build a RsvpAction JSON-LD map.

  ## Fields

  - `:additional_number_of_guests` - If responding yes, the number of guests who will attend in addition to the invitee.
  - `:comment` - Comments, typically from users.
  - `:rsvp_response` - The response (yes, no, maybe) to the RSVP. One of: `:rsvp_response_maybe`, `:rsvp_response_no`, `:rsvp_response_yes`.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.InformAction`
  - `SEO.JSONLD.CommunicateAction`
  - `SEO.JSONLD.Action`
  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_expand_action_io()
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "RsvpAction")
  end
end
