# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.StatisticalPopulation do
  @moduledoc """
  A StatisticalPopulation is a set of instances of a certain given type that satisfy some set of constraints. The property `populationType` is used to specify the type. Any property that can be used on instances of that type can appear on the statistical population. For example, a `SEO.JSONLD.StatisticalPopulation` representing all `SEO.JSONLD.Person`s with a `homeLocation` of East Podunk California would be described by applying the appropriate `homeLocation` and `populationType` properties to a `SEO.JSONLD.StatisticalPopulation` item that stands for that set of people.
  The properties `numConstraints` and `constraintProperty` are used to specify which of the populations properties are used to specify the population. Note that the sense of "population" used here is the general sense of a statistical
  population, and does not imply that the population consists of people. For example, a `populationType` of `SEO.JSONLD.Event` or `SEO.JSONLD.NewsArticle` could be used. See also `SEO.JSONLD.Observation`, where a `populationType` such as `SEO.JSONLD.Person` or `SEO.JSONLD.Event` can be indicated directly. In most cases it may be better to use `SEO.JSONLD.StatisticalVariable` instead of `SEO.JSONLD.StatisticalPopulation`.

  Helper for building a Schema.org [StatisticalPopulation](https://schema.org/StatisticalPopulation) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:population_type) => SEO.JSONLD.Class.t() | map(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              population_type: SEO.JSONLD.Class.t() | map(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"StatisticalPopulation"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{}
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :disambiguating_description => "disambiguatingDescription",
    :main_entity_of_page => "mainEntityOfPage",
    :population_type => "populationType",
    :potential_action => "potentialAction",
    :same_as => "sameAs",
    :subject_of => "subjectOf"
  }

  @doc """
  Build a StatisticalPopulation JSON-LD map.

  ## Fields

  - `:population_type` - Indicates the populationType common to all members of a `SEO.JSONLD.StatisticalPopulation` or all cases within the scope of a `SEO.JSONLD.StatisticalVariable`.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "StatisticalPopulation")
  end
end
