# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.TypeAndQuantityNode do
  @moduledoc """
  A structured value indicating the quantity, unit of measurement, and business function of goods included in a bundle offer.

  Helper for building a Schema.org [TypeAndQuantityNode](https://schema.org/TypeAndQuantityNode) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:amount_of_this_good) => number(),
            optional(:business_function) => term(),
            optional(:type_of_good) => SEO.JSONLD.Service.t() | map() | SEO.JSONLD.Product.t(),
            optional(:unit_code) => String.t() | URI.t(),
            optional(:unit_text) => String.t(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              amount_of_this_good: number(),
              business_function: term(),
              type_of_good: SEO.JSONLD.Service.t() | map() | SEO.JSONLD.Product.t(),
              unit_code: String.t() | URI.t(),
              unit_text: String.t(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"TypeAndQuantityNode"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{
    :business_function => %{}
  }
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :amount_of_this_good => "amountOfThisGood",
    :business_function => "businessFunction",
    :disambiguating_description => "disambiguatingDescription",
    :main_entity_of_page => "mainEntityOfPage",
    :potential_action => "potentialAction",
    :same_as => "sameAs",
    :subject_of => "subjectOf",
    :type_of_good => "typeOfGood",
    :unit_code => "unitCode",
    :unit_text => "unitText"
  }

  @doc """
  Build a TypeAndQuantityNode JSON-LD map.

  ## Fields

  - `:amount_of_this_good` - The quantity of the goods included in the offer.
  - `:business_function` - The business function (e.g. sell, lease, repair, dispose) of the offer or component of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell. One of: .
  - `:type_of_good` - The product that this structured value is referring to.
  - `:unit_code` - The unit of measurement given using the UN/CEFACT Common Code (3 characters) or a URL. Other codes than the UN/CEFACT Common Code may be used with a prefix followed by a colon.
  - `:unit_text` - A string or text indicating the unit of measurement. Useful if you cannot provide a standard unit code for
  unitCode.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "TypeAndQuantityNode")
  end
end
