# This file is generated by priv/gen_json_ld.exs. Do not edit directly.
defmodule SEO.JSONLD.VitalSign do
  @moduledoc """
  Vital signs are measures of various physiological functions in order to assess the most basic body functions.

  Helper for building a Schema.org [VitalSign](https://schema.org/VitalSign) JSON-LD structure.
  """

  @type attrs ::
          %{
            optional(:identifying_exam) =>
              :abdomen
              | :appearance
              | :cardiovascular_exam
              | :ear
              | :eye
              | :genitourinary
              | :head
              | :lung
              | :musculoskeletal_exam
              | :neck
              | :neuro
              | :nose
              | :skin
              | :throat,
            optional(:identifying_test) => SEO.JSONLD.MedicalTest.t() | map(),
            optional(:possible_treatment) =>
              SEO.JSONLD.MedicalTherapy.t()
              | map()
              | SEO.JSONLD.Drug.t()
              | SEO.JSONLD.LifestyleModification.t()
              | SEO.JSONLD.DrugClass.t(),
            optional(:associated_anatomy) =>
              SEO.JSONLD.SuperficialAnatomy.t()
              | map()
              | SEO.JSONLD.AnatomicalStructure.t()
              | SEO.JSONLD.AnatomicalSystem.t(),
            optional(:cause) => SEO.JSONLD.MedicalCause.t() | map(),
            optional(:differential_diagnosis) => SEO.JSONLD.DDxElement.t() | map(),
            optional(:drug) => SEO.JSONLD.Drug.t() | map(),
            optional(:epidemiology) => String.t(),
            optional(:expected_prognosis) => String.t(),
            optional(:natural_progression) => String.t(),
            optional(:pathophysiology) => String.t(),
            optional(:possible_complication) => String.t(),
            optional(:primary_prevention) => SEO.JSONLD.MedicalTherapy.t() | map(),
            optional(:risk_factor) => SEO.JSONLD.MedicalRiskFactor.t() | map(),
            optional(:secondary_prevention) =>
              SEO.JSONLD.DrugClass.t()
              | map()
              | SEO.JSONLD.LifestyleModification.t()
              | SEO.JSONLD.MedicalTherapy.t()
              | SEO.JSONLD.Drug.t(),
            optional(:sign_or_symptom) => SEO.JSONLD.MedicalSignOrSymptom.t() | map(),
            optional(:stage) => SEO.JSONLD.MedicalConditionStage.t() | map(),
            optional(:status) =>
              :event_cancelled
              | :event_moved_online
              | :event_postponed
              | :event_rescheduled
              | :event_scheduled
              | :active_not_recruiting
              | :completed
              | :enrolling_by_invitation
              | :not_yet_recruiting
              | :recruiting
              | :results_available
              | :results_not_available
              | :suspended
              | :terminated
              | :withdrawn
              | String.t(),
            optional(:typical_test) => SEO.JSONLD.MedicalTest.t() | map(),
            optional(:code) => SEO.JSONLD.MedicalCode.t() | map(),
            optional(:funding) => SEO.JSONLD.Grant.t() | map(),
            optional(:guideline) => SEO.JSONLD.MedicalGuideline.t() | map(),
            optional(:legal_status) =>
              SEO.JSONLD.DrugLegalStatus.t()
              | map()
              | :abdomen
              | :active_not_recruiting
              | :anesthesia
              | :appearance
              | :ayurvedic
              | :bacteria
              | :cardiovascular
              | :cardiovascular_exam
              | :case_series
              | :chiropractic
              | :clinician
              | :cohort_study
              | :community_health
              | :completed
              | :cross_sectional
              | :ct
              | :dentistry
              | :dermatologic
              | :dermatology
              | :diagnostic
              | :diet_nutrition
              | :double_blinded_trial
              | :ear
              | :emergency
              | :endocrine
              | :enrolling_by_invitation
              | :evidence_level_a
              | :evidence_level_b
              | :evidence_level_c
              | :eye
              | :fd_acategory_a
              | :fd_acategory_b
              | :fd_acategory_c
              | :fd_acategory_d
              | :fd_acategory_x
              | :fd_anot_evaluated
              | :fungus
              | :gastroenterologic
              | :genetic
              | :genitourinary
              | :geriatric
              | :gynecologic
              | :head
              | :hematologic
              | :homeopathic
              | :infectious
              | :international_trial
              | :laboratory_science
              | :longitudinal
              | :lung
              | :medical_researcher
              | :midwifery
              | :mri
              | :multi_center_trial
              | :multicellular_parasite
              | :musculoskeletal
              | :musculoskeletal_exam
              | :neck
              | :neuro
              | :neurologic
              | :noninvasive_procedure
              | :nose
              | :not_yet_recruiting
              | :nursing
              | :observational
              | :obstetric
              | :oncologic
              | :open_trial
              | :optometric
              | :osteopathic
              | :otc
              | :otolaryngologic
              | :pathology
              | :pediatric
              | :percutaneous_procedure
              | :pet
              | :pharmacy_specialty
              | :physiotherapy
              | :placebo_controlled_trial
              | :plastic_surgery
              | :podiatric
              | :prescription_only
              | :primary_care
              | :prion
              | :protozoa
              | :psychiatric
              | :public_health
              | :pulmonary
              | :radiography
              | :randomized_trial
              | :recruiting
              | :registry
              | :reimbursement_cap
              | :renal
              | :respiratory_therapy
              | :results_available
              | :results_not_available
              | :retail
              | :rheumatologic
              | :single_blinded_trial
              | :single_center_trial
              | :skin
              | :speech_pathology
              | :surgical
              | :suspended
              | :terminated
              | :therapeutic
              | :throat
              | :toxicologic
              | :traditional_chinese
              | :triple_blinded_trial
              | :ultrasound
              | :urologic
              | :virus
              | :western_conventional
              | :wholesale
              | :withdrawn
              | :x_ray
              | String.t(),
            optional(:medicine_system) =>
              :ayurvedic
              | :chiropractic
              | :homeopathic
              | :osteopathic
              | :traditional_chinese
              | :western_conventional,
            optional(:recognizing_authority) => SEO.JSONLD.Organization.t() | map(),
            optional(:relevant_specialty) =>
              :anesthesia
              | :cardiovascular
              | :community_health
              | :dentistry
              | :dermatologic
              | :dermatology
              | :diet_nutrition
              | :emergency
              | :endocrine
              | :gastroenterologic
              | :genetic
              | :geriatric
              | :gynecologic
              | :hematologic
              | :infectious
              | :laboratory_science
              | :midwifery
              | :musculoskeletal
              | :neurologic
              | :nursing
              | :obstetric
              | :oncologic
              | :optometric
              | :otolaryngologic
              | :pathology
              | :pediatric
              | :pharmacy_specialty
              | :physiotherapy
              | :plastic_surgery
              | :podiatric
              | :primary_care
              | :psychiatric
              | :public_health
              | :pulmonary
              | :radiography
              | :renal
              | :respiratory_therapy
              | :rheumatologic
              | :speech_pathology
              | :surgical
              | :toxicologic
              | :urologic,
            optional(:study) => SEO.JSONLD.MedicalStudy.t() | map(),
            optional(:additional_type) => String.t() | URI.t(),
            optional(:alternate_name) => String.t(),
            optional(:description) => SEO.JSONLD.TextObject.t() | map() | String.t(),
            optional(:disambiguating_description) => String.t(),
            optional(:identifier) => String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
            optional(:image) => URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
            optional(:main_entity_of_page) =>
              SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
            optional(:name) => String.t(),
            optional(:owner) => SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
            optional(:potential_action) => SEO.JSONLD.Action.t() | map(),
            optional(:same_as) => URI.t() | String.t(),
            optional(:subject_of) => SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
            optional(:url) => URI.t() | String.t()
          }
          | [
              identifying_exam:
                :abdomen
                | :appearance
                | :cardiovascular_exam
                | :ear
                | :eye
                | :genitourinary
                | :head
                | :lung
                | :musculoskeletal_exam
                | :neck
                | :neuro
                | :nose
                | :skin
                | :throat,
              identifying_test: SEO.JSONLD.MedicalTest.t() | map(),
              possible_treatment:
                SEO.JSONLD.MedicalTherapy.t()
                | map()
                | SEO.JSONLD.Drug.t()
                | SEO.JSONLD.LifestyleModification.t()
                | SEO.JSONLD.DrugClass.t(),
              associated_anatomy:
                SEO.JSONLD.SuperficialAnatomy.t()
                | map()
                | SEO.JSONLD.AnatomicalStructure.t()
                | SEO.JSONLD.AnatomicalSystem.t(),
              cause: SEO.JSONLD.MedicalCause.t() | map(),
              differential_diagnosis: SEO.JSONLD.DDxElement.t() | map(),
              drug: SEO.JSONLD.Drug.t() | map(),
              epidemiology: String.t(),
              expected_prognosis: String.t(),
              natural_progression: String.t(),
              pathophysiology: String.t(),
              possible_complication: String.t(),
              primary_prevention: SEO.JSONLD.MedicalTherapy.t() | map(),
              risk_factor: SEO.JSONLD.MedicalRiskFactor.t() | map(),
              secondary_prevention:
                SEO.JSONLD.DrugClass.t()
                | map()
                | SEO.JSONLD.LifestyleModification.t()
                | SEO.JSONLD.MedicalTherapy.t()
                | SEO.JSONLD.Drug.t(),
              sign_or_symptom: SEO.JSONLD.MedicalSignOrSymptom.t() | map(),
              stage: SEO.JSONLD.MedicalConditionStage.t() | map(),
              status:
                :event_cancelled
                | :event_moved_online
                | :event_postponed
                | :event_rescheduled
                | :event_scheduled
                | :active_not_recruiting
                | :completed
                | :enrolling_by_invitation
                | :not_yet_recruiting
                | :recruiting
                | :results_available
                | :results_not_available
                | :suspended
                | :terminated
                | :withdrawn
                | String.t(),
              typical_test: SEO.JSONLD.MedicalTest.t() | map(),
              code: SEO.JSONLD.MedicalCode.t() | map(),
              funding: SEO.JSONLD.Grant.t() | map(),
              guideline: SEO.JSONLD.MedicalGuideline.t() | map(),
              legal_status:
                SEO.JSONLD.DrugLegalStatus.t()
                | map()
                | :abdomen
                | :active_not_recruiting
                | :anesthesia
                | :appearance
                | :ayurvedic
                | :bacteria
                | :cardiovascular
                | :cardiovascular_exam
                | :case_series
                | :chiropractic
                | :clinician
                | :cohort_study
                | :community_health
                | :completed
                | :cross_sectional
                | :ct
                | :dentistry
                | :dermatologic
                | :dermatology
                | :diagnostic
                | :diet_nutrition
                | :double_blinded_trial
                | :ear
                | :emergency
                | :endocrine
                | :enrolling_by_invitation
                | :evidence_level_a
                | :evidence_level_b
                | :evidence_level_c
                | :eye
                | :fd_acategory_a
                | :fd_acategory_b
                | :fd_acategory_c
                | :fd_acategory_d
                | :fd_acategory_x
                | :fd_anot_evaluated
                | :fungus
                | :gastroenterologic
                | :genetic
                | :genitourinary
                | :geriatric
                | :gynecologic
                | :head
                | :hematologic
                | :homeopathic
                | :infectious
                | :international_trial
                | :laboratory_science
                | :longitudinal
                | :lung
                | :medical_researcher
                | :midwifery
                | :mri
                | :multi_center_trial
                | :multicellular_parasite
                | :musculoskeletal
                | :musculoskeletal_exam
                | :neck
                | :neuro
                | :neurologic
                | :noninvasive_procedure
                | :nose
                | :not_yet_recruiting
                | :nursing
                | :observational
                | :obstetric
                | :oncologic
                | :open_trial
                | :optometric
                | :osteopathic
                | :otc
                | :otolaryngologic
                | :pathology
                | :pediatric
                | :percutaneous_procedure
                | :pet
                | :pharmacy_specialty
                | :physiotherapy
                | :placebo_controlled_trial
                | :plastic_surgery
                | :podiatric
                | :prescription_only
                | :primary_care
                | :prion
                | :protozoa
                | :psychiatric
                | :public_health
                | :pulmonary
                | :radiography
                | :randomized_trial
                | :recruiting
                | :registry
                | :reimbursement_cap
                | :renal
                | :respiratory_therapy
                | :results_available
                | :results_not_available
                | :retail
                | :rheumatologic
                | :single_blinded_trial
                | :single_center_trial
                | :skin
                | :speech_pathology
                | :surgical
                | :suspended
                | :terminated
                | :therapeutic
                | :throat
                | :toxicologic
                | :traditional_chinese
                | :triple_blinded_trial
                | :ultrasound
                | :urologic
                | :virus
                | :western_conventional
                | :wholesale
                | :withdrawn
                | :x_ray
                | String.t(),
              medicine_system:
                :ayurvedic
                | :chiropractic
                | :homeopathic
                | :osteopathic
                | :traditional_chinese
                | :western_conventional,
              recognizing_authority: SEO.JSONLD.Organization.t() | map(),
              relevant_specialty:
                :anesthesia
                | :cardiovascular
                | :community_health
                | :dentistry
                | :dermatologic
                | :dermatology
                | :diet_nutrition
                | :emergency
                | :endocrine
                | :gastroenterologic
                | :genetic
                | :geriatric
                | :gynecologic
                | :hematologic
                | :infectious
                | :laboratory_science
                | :midwifery
                | :musculoskeletal
                | :neurologic
                | :nursing
                | :obstetric
                | :oncologic
                | :optometric
                | :otolaryngologic
                | :pathology
                | :pediatric
                | :pharmacy_specialty
                | :physiotherapy
                | :plastic_surgery
                | :podiatric
                | :primary_care
                | :psychiatric
                | :public_health
                | :pulmonary
                | :radiography
                | :renal
                | :respiratory_therapy
                | :rheumatologic
                | :speech_pathology
                | :surgical
                | :toxicologic
                | :urologic,
              study: SEO.JSONLD.MedicalStudy.t() | map(),
              additional_type: String.t() | URI.t(),
              alternate_name: String.t(),
              description: SEO.JSONLD.TextObject.t() | map() | String.t(),
              disambiguating_description: String.t(),
              identifier: String.t() | URI.t() | SEO.JSONLD.PropertyValue.t() | map(),
              image: URI.t() | String.t() | SEO.JSONLD.ImageObject.t() | map(),
              main_entity_of_page: SEO.JSONLD.CreativeWork.t() | map() | URI.t() | String.t(),
              name: String.t(),
              owner: SEO.JSONLD.Organization.t() | map() | SEO.JSONLD.Person.t(),
              potential_action: SEO.JSONLD.Action.t() | map(),
              same_as: URI.t() | String.t(),
              subject_of: SEO.JSONLD.Event.t() | map() | SEO.JSONLD.CreativeWork.t(),
              url: URI.t() | String.t()
            ]

  @typedoc """
  A JSON-LD map ready to be serialized. String-keyed, always includes
  `"@context"` and `"@type"` set to `"https://schema.org"` and
  `"VitalSign"` respectively, plus any camelCased field keys
  the caller provided (see `build/1`).
  """
  @type t :: %{String.t() => term()}

  @enum_fields %{
    :identifying_exam => %{
      :abdomen => "https://schema.org/Abdomen",
      :appearance => "https://schema.org/Appearance",
      :cardiovascular_exam => "https://schema.org/CardiovascularExam",
      :ear => "https://schema.org/Ear",
      :eye => "https://schema.org/Eye",
      :genitourinary => "https://schema.org/Genitourinary",
      :head => "https://schema.org/Head",
      :lung => "https://schema.org/Lung",
      :musculoskeletal_exam => "https://schema.org/MusculoskeletalExam",
      :neck => "https://schema.org/Neck",
      :neuro => "https://schema.org/Neuro",
      :nose => "https://schema.org/Nose",
      :skin => "https://schema.org/Skin",
      :throat => "https://schema.org/Throat"
    },
    :legal_status => %{
      :abdomen => "https://schema.org/Abdomen",
      :active_not_recruiting => "https://schema.org/ActiveNotRecruiting",
      :anesthesia => "https://schema.org/Anesthesia",
      :appearance => "https://schema.org/Appearance",
      :ayurvedic => "https://schema.org/Ayurvedic",
      :bacteria => "https://schema.org/Bacteria",
      :cardiovascular => "https://schema.org/Cardiovascular",
      :cardiovascular_exam => "https://schema.org/CardiovascularExam",
      :case_series => "https://schema.org/CaseSeries",
      :chiropractic => "https://schema.org/Chiropractic",
      :clinician => "https://schema.org/Clinician",
      :cohort_study => "https://schema.org/CohortStudy",
      :community_health => "https://schema.org/CommunityHealth",
      :completed => "https://schema.org/Completed",
      :cross_sectional => "https://schema.org/CrossSectional",
      :ct => "https://schema.org/CT",
      :dentistry => "https://schema.org/Dentistry",
      :dermatologic => "https://schema.org/Dermatologic",
      :dermatology => "https://schema.org/Dermatology",
      :diagnostic => "https://schema.org/Diagnostic",
      :diet_nutrition => "https://schema.org/DietNutrition",
      :double_blinded_trial => "https://schema.org/DoubleBlindedTrial",
      :ear => "https://schema.org/Ear",
      :emergency => "https://schema.org/Emergency",
      :endocrine => "https://schema.org/Endocrine",
      :enrolling_by_invitation => "https://schema.org/EnrollingByInvitation",
      :evidence_level_a => "https://schema.org/EvidenceLevelA",
      :evidence_level_b => "https://schema.org/EvidenceLevelB",
      :evidence_level_c => "https://schema.org/EvidenceLevelC",
      :eye => "https://schema.org/Eye",
      :fd_acategory_a => "https://schema.org/FDAcategoryA",
      :fd_acategory_b => "https://schema.org/FDAcategoryB",
      :fd_acategory_c => "https://schema.org/FDAcategoryC",
      :fd_acategory_d => "https://schema.org/FDAcategoryD",
      :fd_acategory_x => "https://schema.org/FDAcategoryX",
      :fd_anot_evaluated => "https://schema.org/FDAnotEvaluated",
      :fungus => "https://schema.org/Fungus",
      :gastroenterologic => "https://schema.org/Gastroenterologic",
      :genetic => "https://schema.org/Genetic",
      :genitourinary => "https://schema.org/Genitourinary",
      :geriatric => "https://schema.org/Geriatric",
      :gynecologic => "https://schema.org/Gynecologic",
      :head => "https://schema.org/Head",
      :hematologic => "https://schema.org/Hematologic",
      :homeopathic => "https://schema.org/Homeopathic",
      :infectious => "https://schema.org/Infectious",
      :international_trial => "https://schema.org/InternationalTrial",
      :laboratory_science => "https://schema.org/LaboratoryScience",
      :longitudinal => "https://schema.org/Longitudinal",
      :lung => "https://schema.org/Lung",
      :medical_researcher => "https://schema.org/MedicalResearcher",
      :midwifery => "https://schema.org/Midwifery",
      :mri => "https://schema.org/MRI",
      :multi_center_trial => "https://schema.org/MultiCenterTrial",
      :multicellular_parasite => "https://schema.org/MulticellularParasite",
      :musculoskeletal => "https://schema.org/Musculoskeletal",
      :musculoskeletal_exam => "https://schema.org/MusculoskeletalExam",
      :neck => "https://schema.org/Neck",
      :neuro => "https://schema.org/Neuro",
      :neurologic => "https://schema.org/Neurologic",
      :noninvasive_procedure => "https://schema.org/NoninvasiveProcedure",
      :nose => "https://schema.org/Nose",
      :not_yet_recruiting => "https://schema.org/NotYetRecruiting",
      :nursing => "https://schema.org/Nursing",
      :observational => "https://schema.org/Observational",
      :obstetric => "https://schema.org/Obstetric",
      :oncologic => "https://schema.org/Oncologic",
      :open_trial => "https://schema.org/OpenTrial",
      :optometric => "https://schema.org/Optometric",
      :osteopathic => "https://schema.org/Osteopathic",
      :otc => "https://schema.org/OTC",
      :otolaryngologic => "https://schema.org/Otolaryngologic",
      :pathology => "https://schema.org/Pathology",
      :pediatric => "https://schema.org/Pediatric",
      :percutaneous_procedure => "https://schema.org/PercutaneousProcedure",
      :pet => "https://schema.org/PET",
      :pharmacy_specialty => "https://schema.org/PharmacySpecialty",
      :physiotherapy => "https://schema.org/Physiotherapy",
      :placebo_controlled_trial => "https://schema.org/PlaceboControlledTrial",
      :plastic_surgery => "https://schema.org/PlasticSurgery",
      :podiatric => "https://schema.org/Podiatric",
      :prescription_only => "https://schema.org/PrescriptionOnly",
      :primary_care => "https://schema.org/PrimaryCare",
      :prion => "https://schema.org/Prion",
      :protozoa => "https://schema.org/Protozoa",
      :psychiatric => "https://schema.org/Psychiatric",
      :public_health => "https://schema.org/PublicHealth",
      :pulmonary => "https://schema.org/Pulmonary",
      :radiography => "https://schema.org/Radiography",
      :randomized_trial => "https://schema.org/RandomizedTrial",
      :recruiting => "https://schema.org/Recruiting",
      :registry => "https://schema.org/Registry",
      :reimbursement_cap => "https://schema.org/ReimbursementCap",
      :renal => "https://schema.org/Renal",
      :respiratory_therapy => "https://schema.org/RespiratoryTherapy",
      :results_available => "https://schema.org/ResultsAvailable",
      :results_not_available => "https://schema.org/ResultsNotAvailable",
      :retail => "https://schema.org/Retail",
      :rheumatologic => "https://schema.org/Rheumatologic",
      :single_blinded_trial => "https://schema.org/SingleBlindedTrial",
      :single_center_trial => "https://schema.org/SingleCenterTrial",
      :skin => "https://schema.org/Skin",
      :speech_pathology => "https://schema.org/SpeechPathology",
      :surgical => "https://schema.org/Surgical",
      :suspended => "https://schema.org/Suspended",
      :terminated => "https://schema.org/Terminated",
      :therapeutic => "https://schema.org/Therapeutic",
      :throat => "https://schema.org/Throat",
      :toxicologic => "https://schema.org/Toxicologic",
      :traditional_chinese => "https://schema.org/TraditionalChinese",
      :triple_blinded_trial => "https://schema.org/TripleBlindedTrial",
      :ultrasound => "https://schema.org/Ultrasound",
      :urologic => "https://schema.org/Urologic",
      :virus => "https://schema.org/Virus",
      :western_conventional => "https://schema.org/WesternConventional",
      :wholesale => "https://schema.org/Wholesale",
      :withdrawn => "https://schema.org/Withdrawn",
      :x_ray => "https://schema.org/XRay"
    },
    :medicine_system => %{
      :ayurvedic => "https://schema.org/Ayurvedic",
      :chiropractic => "https://schema.org/Chiropractic",
      :homeopathic => "https://schema.org/Homeopathic",
      :osteopathic => "https://schema.org/Osteopathic",
      :traditional_chinese => "https://schema.org/TraditionalChinese",
      :western_conventional => "https://schema.org/WesternConventional"
    },
    :relevant_specialty => %{
      :anesthesia => "https://schema.org/Anesthesia",
      :cardiovascular => "https://schema.org/Cardiovascular",
      :community_health => "https://schema.org/CommunityHealth",
      :dentistry => "https://schema.org/Dentistry",
      :dermatologic => "https://schema.org/Dermatologic",
      :dermatology => "https://schema.org/Dermatology",
      :diet_nutrition => "https://schema.org/DietNutrition",
      :emergency => "https://schema.org/Emergency",
      :endocrine => "https://schema.org/Endocrine",
      :gastroenterologic => "https://schema.org/Gastroenterologic",
      :genetic => "https://schema.org/Genetic",
      :geriatric => "https://schema.org/Geriatric",
      :gynecologic => "https://schema.org/Gynecologic",
      :hematologic => "https://schema.org/Hematologic",
      :infectious => "https://schema.org/Infectious",
      :laboratory_science => "https://schema.org/LaboratoryScience",
      :midwifery => "https://schema.org/Midwifery",
      :musculoskeletal => "https://schema.org/Musculoskeletal",
      :neurologic => "https://schema.org/Neurologic",
      :nursing => "https://schema.org/Nursing",
      :obstetric => "https://schema.org/Obstetric",
      :oncologic => "https://schema.org/Oncologic",
      :optometric => "https://schema.org/Optometric",
      :otolaryngologic => "https://schema.org/Otolaryngologic",
      :pathology => "https://schema.org/Pathology",
      :pediatric => "https://schema.org/Pediatric",
      :pharmacy_specialty => "https://schema.org/PharmacySpecialty",
      :physiotherapy => "https://schema.org/Physiotherapy",
      :plastic_surgery => "https://schema.org/PlasticSurgery",
      :podiatric => "https://schema.org/Podiatric",
      :primary_care => "https://schema.org/PrimaryCare",
      :psychiatric => "https://schema.org/Psychiatric",
      :public_health => "https://schema.org/PublicHealth",
      :pulmonary => "https://schema.org/Pulmonary",
      :radiography => "https://schema.org/Radiography",
      :renal => "https://schema.org/Renal",
      :respiratory_therapy => "https://schema.org/RespiratoryTherapy",
      :rheumatologic => "https://schema.org/Rheumatologic",
      :speech_pathology => "https://schema.org/SpeechPathology",
      :surgical => "https://schema.org/Surgical",
      :toxicologic => "https://schema.org/Toxicologic",
      :urologic => "https://schema.org/Urologic"
    },
    :status => %{
      :active_not_recruiting => "https://schema.org/ActiveNotRecruiting",
      :completed => "https://schema.org/Completed",
      :enrolling_by_invitation => "https://schema.org/EnrollingByInvitation",
      :event_cancelled => "https://schema.org/EventCancelled",
      :event_moved_online => "https://schema.org/EventMovedOnline",
      :event_postponed => "https://schema.org/EventPostponed",
      :event_rescheduled => "https://schema.org/EventRescheduled",
      :event_scheduled => "https://schema.org/EventScheduled",
      :not_yet_recruiting => "https://schema.org/NotYetRecruiting",
      :recruiting => "https://schema.org/Recruiting",
      :results_available => "https://schema.org/ResultsAvailable",
      :results_not_available => "https://schema.org/ResultsNotAvailable",
      :suspended => "https://schema.org/Suspended",
      :terminated => "https://schema.org/Terminated",
      :withdrawn => "https://schema.org/Withdrawn"
    }
  }
  @key_map %{
    :additional_type => "additionalType",
    :alternate_name => "alternateName",
    :associated_anatomy => "associatedAnatomy",
    :differential_diagnosis => "differentialDiagnosis",
    :disambiguating_description => "disambiguatingDescription",
    :expected_prognosis => "expectedPrognosis",
    :identifying_exam => "identifyingExam",
    :identifying_test => "identifyingTest",
    :legal_status => "legalStatus",
    :main_entity_of_page => "mainEntityOfPage",
    :medicine_system => "medicineSystem",
    :natural_progression => "naturalProgression",
    :possible_complication => "possibleComplication",
    :possible_treatment => "possibleTreatment",
    :potential_action => "potentialAction",
    :primary_prevention => "primaryPrevention",
    :recognizing_authority => "recognizingAuthority",
    :relevant_specialty => "relevantSpecialty",
    :risk_factor => "riskFactor",
    :same_as => "sameAs",
    :secondary_prevention => "secondaryPrevention",
    :sign_or_symptom => "signOrSymptom",
    :subject_of => "subjectOf",
    :typical_test => "typicalTest"
  }

  @doc """
  Build a VitalSign JSON-LD map.

  ## Fields

  This type has no own properties. See the inherited properties below.

  ### Inherited properties

  Additional properties are available through the inheritance chain. See
  each ancestor's docs for its properties:

  - `SEO.JSONLD.MedicalSign`
  - `SEO.JSONLD.MedicalSignOrSymptom`
  - `SEO.JSONLD.MedicalCondition`
  - `SEO.JSONLD.MedicalEntity`
  - `SEO.JSONLD.Thing`
  """
  @spec build(attrs()) :: t()
  def build(attrs) do
    attrs
    |> Enum.into(%{})
    |> SEO.Utils.build_convert_enums(@enum_fields)
    |> SEO.Utils.build_coerce_structs()
    |> SEO.Utils.build_camelize_keys(@key_map)
    |> Map.put_new("@context", "https://schema.org")
    |> Map.put_new("@type", "VitalSign")
  end
end
